In [1]:
from IPython.display import display, HTML

display(HTML("""
<style>

/* =========================
   전체 레이아웃
========================= */

div.container{
    width:85% !important;
}

div.cell.code_cell.rendered{
    width:100%;
}

div.input_prompt{
    padding:0;
}

div.prompt{
    min-width:70px;
}

div#toc-wrapper{
    padding-top:120px;
}

table.dataframe{
    font-size:12px;
}

/* =========================
   코드 입력창
========================= */

div.CodeMirror{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
    line-height:1.6;
}

/* =========================
   입력 셀
========================= */

div.input{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   코드 출력
========================= */

div.output{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   Markdown 전체
========================= */

.rendered_html{
    font-family:"마루 부리OTF 중간" !important;
    font-size:18px !important;
    line-height:1.8;
}

/* 제목 */

.rendered_html h1,
.rendered_html h2,
.rendered_html h3,
.rendered_html h4,
.rendered_html h5,
.rendered_html h6{
    font-family:"마루 부리OTF 조금굵은" !important;
}

/* 본문 */

.rendered_html p{
    font-family:"마루 부리OTF 중간" !important;
}

/* 리스트 */

.rendered_html li{
    font-family:"마루 부리OTF 중간" !important;
    padding:5px;
}

/* 인용 */

.rendered_html blockquote{
    font-family:"마루 부리OTF 중간" !important;
}

/* 표 */

.rendered_html table{
    font-family:"마루 부리OTF 중간" !important;
}

/* 코드 블록 */

.rendered_html pre,
.rendered_html code{
    font-family:"Consolas" !important;
    font-size:12pt !important;
}

</style>
"""))

<font size="6" color="red"><b>ch14. 웹 데이터 수집</b></font>
# 1절. BeautifulSoup과 parser
    (정석 웹크롤링, 공공api사용)

`pip install bs4` 아나콘다를 설치하면 자동 설치되는 패키지에 포함
- 공식 사이트 : https://www.crummy.com/software/BeautifulSoup/
- documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [2]:
import requests # HTTP요청 처리하는 lib러리
# file:// == c:
# https://www.
from requests_file import FileAdapter # 대문자 시작은 클래스명

In [3]:
# 로컬에 있는 파일을 웹요청하듯이 읽어오는 작업
s = requests.Session()
s.mount("file://", FileAdapter()) # file://로 시작하는 url을 어댑터가 처리
response = s.get("file:///ai/source/01_python/data/ch14_sample.html") # C:\ai\source\01_python\data\ch14_sample.html
response

In [4]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [5]:
response.status_code
# 200 : 정상
# 404 : 없는 페이지
# 406 : 요청한 형식대로 줄수없어서 응답을 거부 (ex : JSON형식으로 줘 -> HTML 형식밖에 없는데?)

200

In [6]:
response.content # html의 바이너리 형식의 내용

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [7]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [8]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [9]:
# html 파싱 객체
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, #response.content,
                    "html.parser")
# soup

In [10]:
# 1. soup.select_one('선택자') : 해당 선택자 처음 하나 엘리먼트만
el = soup.select_one('h1.css')
print('el =', el)
print('el.text =>', el.text)
print('el.string =>', el.string)
print('el의 속성들 =>', el.attrs)
print('el의 class속성 =>', el.attrs['class'])
print('el의 class속성 =>', el.attrs.get('class'))
# (없는 속성은 에러) print('el의 href속성 =>', el.attrs.get['href'])
print('el의 href속성 =>', el.attrs.get('href'))
print('el의 name =>', el.name)

el = <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text => Hello, CSS
el.string => Hello, CSS
el의 속성들 => {'class': ['greeting', 'css'], 'id': 'text'}
el의 class속성 => ['greeting', 'css']
el의 class속성 => ['greeting', 'css']
el의 href속성 => None
el의 name => h1

In [11]:
# 2. soup.select('선택자') : 해당 선택자 엘리먼트 다 list로
els = soup.select('h1.css')
print('els =>', els)
# 중복된 요청사항을 select_one이 아닌 select로 요청하면 해당 사항을 전부 다 출력
print('els들의 text =>', [el.text for el in els])
print('els들의 string =>', [el.string for el in els])
print('els들의 속성들 =>', [el.attrs for el in els])
print('els들의 class 속성 =>', [el.attrs.get('class') for el in els])

els => [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text => ['Hello, CSS', 'Hi, CSS']
els들의 string => ['Hello, CSS', 'Hi, CSS']
els들의 속성들 => [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class 속성 => [['greeting', 'css'], ['css']]

In [12]:
# 3. soup.find(태그, 속성) vs soup.select_one('선택자') : 해당 속성을 갖은 택 처음 하나만
print('select_one :', soup.select_one('h1.css'))
print('find            :', soup.find('h1', {'class':'css'}))
print('find            :', soup.find('h1', class_='css'))
print()
print('select_one :', soup.select_one('h1#text'))
print('select_one :', soup.find('h1#'))

select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>
find            : <h1 class="greeting css" id="text">Hello, CSS</h1>
find            : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one : None

In [13]:
# 4. soup.find_all(태그, 속성) vs soup.select('선택자') : 해당 엘리먼트 다 list로
print('모든 h1.css.greeting와 span태그 :', soup.select('h1.css.greeting, span'))
print('모든 h1.css와 span태그 :', soup.find_all(['h1'], class_='css')+soup.find_all('span'))

모든 h1.css.greeting와 span태그 : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css와 span태그 : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [14]:
# 없는 엘리먼트 찾기
print('find_all(빈list) :', soup.find_all('a'))
print('find(None)      :', soup.find('a'))
print('select(빈list) :', soup.select('a'))
print('select_one(None) :', soup.select_one('a'))

find_all(빈list) : []
find(None)      : None
select(빈list) : []
select_one(None) : None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
## 2.1 BeautifulSoup 모듈을 활용한 html 웹 데이터 수집
### 1) 환율정보 가져오기(네이버증권 -> 시장지표)

- https://finance.naver.com/marketindex/
    * 크롤링 허용범위는 사이트마다 ~/robots.txt에서 확인할 수 있음
       * Allow : 크롤링 허용가능한 폴더
       * Disallow : 크롤링 제한 폴더

In [15]:
# soup객체 생성 방법 1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
# response # Response 객체
print(response.status_code)
# response.text #response.content
soup = BeautifulSoup(response.text, 'html.parser')
soup

200

<script language="javascript" src="/template/head_js.naver?referer=info.finance.naver.com&amp;menu=marketindex&amp;submenu=market"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260731153938/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260731153938/js/jindo.1.5.3.element-text-patch.js" type="text/javascript"></script>
<div id="container" style="padding-bottom:0px;">
<div class="market_include">
<div class="market_data">
<div class="market1">
<div class="title">
<h2 class="h_market1"><span>환전 고시 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="exchangeList">
<li class="on">
<a class="head usd" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdt', '', '', event);">
<h3 class="h_lst"><span class="blind">미국 USD</span></h3>
<div class="head_info point_dn">
<span class="value">1,411.90</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 7.10</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.13 09:33</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">66</span>회</span>
</div>
</li>
<li class="">
<a class="head jpy" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyt', '', '', event);">
<h3 class="h_lst"><span class="blind">일본 JPY(100엔)</span></h3>
<div class="head_info point_dn">
<span class="value">886.23</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 3.98</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_JPYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.13 09:33</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">66</span>회</span>
</div>
</li>
<li class="">
<a class="head eur" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurt', '', '', event);">
<h3 class="h_lst"><span class="blind">유럽연합 EUR</span></h3>
<div class="head_info point_dn">
<span class="value">1,627.99</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 7.62</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.13 09:33</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">66</span>회</span>
</div>
</li>
<li class="">
<a class="head cny" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyt', '', '', event);">
<h3 class="h_lst"><span class="blind">중국 CNY</span></h3>
<div class="head_info point_dn">
<span class="value">209.38</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.99</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_CNYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.13 09:33</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">66</span>회</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market2">
<div class="title">
<h2 class="h_market2"><span>국제 시장 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="worldExchangeList">
<li class="on">
<a class="head jpy_usd" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyut', '', '', event);">
<h3 class="h_lst"><span class="blind">달러/일본 엔</span></h3>
<div class="head_info point_dn">
<span class="value">159.2300</span>
<span class="txt_jpy"><span class="blind">엔</span></span>
<span class="change"> 0.0100</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyuc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDJPY.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.12</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_eur" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdt', '', '', event);">
<h3 class="h_lst"><span class="blind">유로/달러</span></h3>
<div class="head_info head_info">
<span class="value">1.1541</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.0000</span>
<span class="blind">보합</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.12</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_gbp" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdt', '', '', event);">
<h3 class="h_lst"><span class="blind">영국 파운드/달러</span></h3>
<div class="head_info point_up">
<span class="value">1.3508</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.0001</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_GBPUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.12</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_idx" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indt', '', '', event);">
<h3 class="h_lst"><span class="blind">달러인덱스</span></h3>
<div class="head_info point_up">
<span class="value">99.8900</span>
<span class="change">0.1800</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDX.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.12</span>
<span class="source">ICE 기준</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market3">
<div class="title">
<h2 class="h_market3"><span>유가·금시세</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="oilGoldList">
<li class="on">
<a class="head wti" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtit', '', '', event);">
<h3 class="h_lst"><span class="blind">WTI</span></h3>
<div class="head_info point_up">
<span class="value">83.27</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.07</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtic', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_CL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.12</span>
<span class="source">NYMEX(뉴욕상업거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gasoline" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilt', '', '', event);">
<h3 class="h_lst"><span class="blind">휘발유</span></h3>
<div class="head_info point_dn">
<span class="value">1863.64</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.06</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_GSL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.13</span>
<span class="source">한국석유공사 Opinet 기준</span>
</div>
</li>
<li class="">
<a class="head gold_inter" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국제 금</span></h3>
<div class="head_info point_up">
<span class="value">4467.5</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">26.40</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GC.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.12</span>
<span class="source">COMEX(뉴욕상품거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gold_domestic" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국내 금</span></h3>
<div class="head_info point_up">
<span class="value">201114.68</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">277.72</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.08.13 09:29</span>
<span class="source">신한은행 기준</span>
							(<span class="num">34</span>회차)
					</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
</div>
</div>
<div class="marketindex_content _replaceNewsLink" id="content">
<div class="section_news">
<h3 class="h_market"><span>환율 주요뉴스</span></h3>
<div class="list_area">
<ul>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=011&amp;article_id=0004651260" onclick="clickcr(this, 'mhn.list', '011_0004651260', '0', event);">공장 짓다 멈추는 반도체 규제 손본다…“4</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.13 08:34</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=277&amp;article_id=0005802287" onclick="clickcr(this, 'mhn.list', '277_0005802287', '1', event);">KB국민은행, 36억 규모 금융사고 발생</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 17:27</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=011&amp;article_id=0004651072" onclick="clickcr(this, 'mhn.list', '011_0004651072', '2', event);">원·달러 환율 소폭 하락…외인 주식 매수에</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 16:42</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0016247767" onclick="clickcr(this, 'mhn.list', '001_0016247767', '3', event);">환율 나흘째 1,410원대…수출기업 달러 </a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 16:01</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=277&amp;article_id=0005802220" onclick="clickcr(this, 'mhn.list', '277_0005802220', '4', event);">원·달러 환율, 0.3원 내린 1415.7</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 15:34</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0016247612" onclick="clickcr(this, 'mhn.list', '001_0016247612', '5', event);">엔화 가치 측정 '돈까스 카레 지수' 등장</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 15:31</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=011&amp;article_id=0004650970" onclick="clickcr(this, 'mhn.list', '011_0004650970', '6', event);">국세청, 상습 고액 체납자에 ‘기업 저승사</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 11:04</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0016246407" onclick="clickcr(this, 'mhn.list', '001_0016246407', '7', event);">하나은행, 삼성동에 외환자본거래센터…해외투</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 10:34</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=011&amp;article_id=0004650927" onclick="clickcr(this, 'mhn.list', '011_0004650927', '8', event);">美 장기금리 다시 4.7% 돌파…베선트 안</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 10:01</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0016246184" onclick="clickcr(this, 'mhn.list', '001_0016246184', '9', event);">하나은행, 외환자본거래센터 개점</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>08.12 09:35</span>
</li>
</ul>
</div>
<a class="btn_more" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429" onclick="clickcr(this, 'mhn.more', '', '', event);"><img alt="더보기" height="18" src="https://ssl.pstatic.net/static/nfinance/btn_more.gif" width="34"/></a>
</div>
<div class="tab_default1" id="tab_section">
<ul>
<li class="on"><a href="./?tabSel=exchange#tab_section" onclick="clickcr(this, 'mtb.exnoti', '', '', event);"><span class="tab1">환전고시 환율</span></a></li>
<li class=""><a href="./?tabSel=worldExchange#tab_section" onclick="clickcr(this, 'mtb.interex', '', '', event);"><span class="tab2">국제시장 환율</span></a></li>
<li class=""><a href="./?tabSel=gold#tab_section" onclick="clickcr(this, 'mtb.oilgold', '', '', event);"><span class="tab3">유가 금시세</span></a></li>
<li class=""><a href="./?tabSel=materials#tab_section" onclick="clickcr(this, 'mtb.material', '', '', event);"><span class="tab4">원자재</span></a></li>
</ul>
<h2 class="blind">환전고시 환율</h2>
</div>
<div class="section_calculator">
<h3 class="h_calculator"><span>환율계산기 (매매기준율 기준)</span></h3>
<div class="calculator">
<div class="inner">
<div class="input">
<div class="selectbox-noscript" id="sInput">
<select class="selectbox-source" id="select_from">
<option label="1" value="1">대한민국 원 KRW</option>
<option class="selectbox-default" label="1" selected="selected" value="1411.6"> 미국 달러 USD</option>
<option label="1" value="1411.6"> 미국 달러 USD</option>
<option label="1" value="1627.72"> 유럽연합 유로 EUR</option>
<option label="100" value="8.8613"> 일본 엔 JPY</option>
<option label="1" value="209.34"> 중국 위안 CNY</option>
<option label="1" value="179.9"> 홍콩 달러 HKD</option>
<option label="1" value="43.82"> 대만 달러 TWD</option>
<option label="1" value="1905.66"> 영국 파운드 GBP</option>
<option label="1" value="3666.3"> 오만 리알 OMR</option>
<option label="1" value="1012.77"> 캐나다 달러 CAD</option>
<option label="1" value="1737.14"> 스위스 프랑 CHF</option>
<option label="1" value="147.4"> 스웨덴 크로나 SEK</option>
<option label="1" value="997.01"> 호주 달러 AUD</option>
<option label="1" value="827.41"> 뉴질랜드 달러 NZD</option>
<option label="1" value="67.19"> 체코 코루나 CZK</option>
<option label="1" value="1.54"> 칠레 페소 CLP</option>
<option label="1" value="29.55"> 튀르키예 뉴리라 TRY</option>
<option label="1" value="0.39"> 몽골 투그릭 MNT</option>
<option label="1" value="473.71"> 이스라엘 세켈 ILS</option>
<option label="1" value="217.73"> 덴마크 크로네 DKK</option>
<option label="1" value="148.67"> 노르웨이 크로네 NOK</option>
<option label="1" value="375.97"> 사우디아라비아 리얄 SAR</option>
<option label="1" value="4566.81"> 쿠웨이트 디나르 KWD</option>
<option label="1" value="3744.0"> 바레인 디나르 BHD</option>
<option label="1" value="384.35"> 아랍에미리트 디르함 AED</option>
<option label="1" value="1990.97"> 요르단 디나르 JOD</option>
<option label="1" value="28.11"> 이집트 파운드 EGP</option>
<option label="1" value="42.69"> 태국 바트 THB</option>
<option label="1" value="1103.29"> 싱가포르 달러 SGD</option>
<option label="1" value="345.35"> 말레이시아 링깃 MYR</option>
<option label="100" value="0.079"> 인도네시아 루피아 IDR</option>
<option label="1" value="387.19"> 카타르 리얄 QAR</option>
<option label="1" value="3.04"> 카자흐스탄 텡게 KZT</option>
<option label="1" value="1103.29"> 브루나이 달러 BND</option>
<option label="1" value="14.81"> 인도 루피 INR</option>
<option label="1" value="5.08"> 파키스탄 루피 PKR</option>
<option label="1" value="11.46"> 방글라데시 타카 BDT</option>
<option label="1" value="23.08"> 필리핀 페소 PHP</option>
<option label="1" value="82.77"> 멕시코 페소 MXN</option>
<option label="1" value="271.93"> 브라질 레알 BRL</option>
<option label="100" value="0.0542"> 베트남 동 VND</option>
<option label="1" value="87.53"> 남아프리카 공화국 랜드 ZAR</option>
<option label="1" value="17.07"> 러시아 루블 RUB</option>
<option label="1" value="4.47"> 헝가리 포린트 HUF</option>
<option label="1" value="378.04"> 폴란드 즈워티 PLN</option>
<option label="1" value="4.23"> 스리랑카 루피 LKR</option>
<option label="1" value="10.62"> 알제리 알제리 디나르 DZD</option>
<option label="1" value="10.92"> 케냐 실링 KES</option>
<option label="1" value="0.45"> 콜롬비아 페소 COP</option>
<option label="1" value="0.53"> 탄자니아 실링 TZS</option>
<option label="1" value="9.25"> 네팔 루피 NPR</option>
<option label="1" value="310.9"> 루마니아 레우 RON</option>
<option label="1" value="221.24"> 리비아 리비아 디나르 LYD</option>
<option label="1" value="174.57"> 마카오 파타카 MOP</option>
<option label="1" value="0.67"> 미얀마 짯 MMK</option>
<option label="1" value="8.79"> 에티오피아 비르 ETB</option>
<option label="1" value="0.12"> 우즈베키스탄 숨 UZS</option>
<option label="1" value="0.35"> 캄보디아 리엘 KHR</option>
<option label="1" value="637.97"> 피지 피지 달러 FJD</option>
</select>
<div class="selectbox-box" onclick="clickcr(this, 'exl*c.clist1', '', '', event);">
<div class="selectbox-label"></div>
</div>
<div class="selectbox-layer ly_calculator">
<div class="selectbox-list"></div>
</div>
</div>
<div class="input_area" id="input_from">
<input id="input_from_money" maxlength="10" onclick="clickcr(this, 'exl*c.unit1', '', '', event);" onfocus="changeActiveInput('from', 'to'); return false;" onkeyup="calcExchange('from', 'to', 'on', event);" type="text" value="1"/>
<img alt="" height="13" id="img_from_monetary" src="https://ssl.pstatic.net/static/nfinance/img_money_USD.gif" width="26"/>
</div>
</div>
<div class="same"><img alt="" height="15" src="https://ssl.pstatic.net/static/nfinance/ico_same.gif" width="28"/></div>
<div class="view">
<div class="selectbox-noscript" id="sView">
<select class="selectbox-source" id="select_to">

In [16]:
# soup객체 생성 방법 2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
# response # HTTPResponse
print(response.status)
# print(response.read().decode('cp949'))
soup = BeautifulSoup(response, 'html.parser')

200

In [17]:
p = '1,1417,000.70'
float(p.replace(',', '')) # 방법 1
float(''.join(p.split(','))) # 방법 2

11417000.7

In [18]:
# div.head_info 밑의 span.value (find계열)
prices = []
headinfos = soup.find_all('div', class_='head_info')
for headinfo in headinfos:
    #print(headinfo)
    #print('------------------------------------------------------------')
    price = headinfo.find('span', class_='value')
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1411.6, 886.13, 1627.72, 209.34, 159.23, 1.1541, 1.3508, 99.89, 83.27, 1863.64, 4467.5, 201114.68]

In [19]:
# span.value (find계열)
price_els = soup.find_all('span', class_='value')
prices = [round(float(price.text.replace(',', '')), 1) for price in price_els]
print(prices)

[1411.6, 886.1, 1627.7, 209.3, 159.2, 1.2, 1.4, 99.9, 83.3, 1863.6, 4467.5, 201114.7]

In [20]:
# div.head_info 밑의 span.value 
price_els = soup.select('div.head_info > span.value')
len(price_els)

12

In [21]:
title_els = soup.select('h3.h_lst > span.blind')
len(title_els)

12

In [22]:
# 단위들 : div.head_info / span.blind
unit_els = soup.select('div.head_info > span > span.blind')
len(unit_els)
units = [unit_el.string for unit_el in unit_els]
units.insert(7, '')
len(units)

12

In [23]:
# 상승/하락 : div.head_info > span.blind
trend_els = soup.select('div.head_info > span.blind')
len(trend_els)

12

In [24]:
len(title_els), len(price_els), len(units), len(trend_els)

(12, 12, 12, 12)

In [25]:
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    print("{} : {}{} - {}".format(title.text, price.text, unit, trend.text))

미국 USD : 1,411.60원 - 하락
일본 JPY(100엔) : 886.13원 - 하락
유럽연합 EUR : 1,627.72원 - 하락
중국 CNY : 209.34원 - 하락
달러/일본 엔 : 159.2300엔 - 하락
유로/달러 : 1.1541달러 - 보합
영국 파운드/달러 : 1.3508달러 - 상승
달러인덱스 : 99.8900 - 상승
WTI : 83.27달러 - 상승
휘발유 : 1863.64원 - 하락
국제 금 : 4467.5달러 - 상승
국내 금 : 201114.68원 - 상승

In [26]:
import pandas as pd;
data = []
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append({'title' : title.text, 'price' : (price.text.replace(',', '')), 'unit' : unit, 'trend' : trend.text})
pd.DataFrame(data).tail()#.to_csv('data/file.csv', index=False)

    title      price unit trend
7   달러인덱스    99.8900         상승
8     WTI      83.27   달러    상승
9     휘발유    1863.64    원    하락
10   국제 금     4467.5   달러    상승
11   국내 금  201114.68    원    상승

In [27]:
data = []
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append([title.text, float(price.text.replace(',','')), unit, trend.text])
pd.DataFrame(data, columns=['title','price','unit','trend'])

           title        price unit trend
0         미국 USD    1411.6000    원    하락
1   일본 JPY(100엔)     886.1300    원    하락
2       유럽연합 EUR    1627.7200    원    하락
3         중국 CNY     209.3400    원    하락
4        달러/일본 엔     159.2300    엔    하락
5          유로/달러       1.1541   달러    보합
6      영국 파운드/달러       1.3508   달러    상승
7          달러인덱스      99.8900         상승
8            WTI      83.2700   달러    상승
9            휘발유    1863.6400    원    하락
10          국제 금    4467.5000   달러    상승
11          국내 금  201114.6800    원    상승

### 2) 이번주 로또번호 출력
- 방법2에서 User-Agent를 추가하여 soup생성

- https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=lotto (다음에서 lotto검색)

```
       1236회(2026.08.08 추첨)
       당첨번호 [12, 18, 21, 29, 34, 38]
       보너스 10
```

In [28]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=lotto'
response = requests.get(url)
print('response의 상태 :', response.status_code)
soup = BeautifulSoup(response.text, 'html.parser')
len(soup)

response의 상태 : 200

4

In [29]:
# 방법2
from urllib.request import urlopen, Request
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)
response = urlopen(request)
print(' 현재 상태 코드 :', response.status)
soup = BeautifulSoup(response, 'html.parser')
soup

 현재 상태 코드 : 200

<!DOCTYPE html>

<html lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://a9.com/-/spec/opensearch/1.1/">
<meta content="text/html;charset=utf-8" http-equiv="content-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="off" name="autocomplete"/>
<meta content="always" name="referrer"/>
<meta content="telephone=no,address=no,email=no" name="format-detection">
<meta content="lotto – Daum 검색" property="og:title"/>
<meta content="https://search.daum.net/search?nil_suggest=btn&amp;w=tot&amp;DA=SBC&amp;q=lotto" property="og:url"/>
<meta content="Daum 검색에서 lotto에 대한 최신정보를 찾아보세요." property="og:description"/>
<meta content="https://search1.daumcdn.net/search/statics/common/img/2026/daum_og.png" property="og:image"/>
<meta content="다음검색" property="og:site_name"/>
<link href="https://search1.daumcdn.net/search/statics/common/img/2026/0303/favicon.ico" rel="shortcut icon"/>
<link href="//sl.search.daum.net/" rel="preconnect"/>
<link href="//ssl.daumcdn.net/" rel="preconnect"/>
<link href="//t1.daumcdn.net/" rel="preconnect"/>
<link href="//wat.ad.daum.net/" rel="preconnect"/>
<link href="//track.tiara.daum.net/" rel="preconnect"/>
<link href="//webid.ad.daum.net/" rel="preconnect"/>
<link href="//webid.kakao.com/" rel="preconnect"/>
<title>lotto – Daum 검색</title>
<link href="//search.daum.net/OpenSearch.xml" rel="search" title="Daum" type="application/opensearchdescription+xml"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/font/pretendard/static/pretendard-dynamic-subset.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_common.0803091025.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_component.0721094041.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/pm_common.0724103702.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/q_comm.0625022346.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/js/fe/dds-workspace/css/2.2.1/dds.min.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20260622160606/cubic.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_collection.0202081129.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_collection2.0706103558.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_lottoColl.0728123112.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_n0nlColl.0213073457.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/p_adLinkColl.0910022655.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/em1Coll.0728123112.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="https://search1.daumcdn.net/search/statics/common/css/2026/p_shoppingColl.0803012615.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_newsColl.0803092251.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_poiColl.0728123112.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/rtlColl.0708073340.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
var uk = "a0a983df-663d-4162-a04f-42c20990cfb8";
var mk = "a0a983df-663d-4162-a04f-42c20990cfb8";
var ksk = "a0a983df-663d-4162-a04f-42c20990cfb8";
var ud = "";
var uuid = "";
var adid = "";
var adid_enabled = "N";
var viewio = "i";
var viewsite = "";
var ServerTime = "20260813093502";
var utf8Query = encodeURIComponent("lotto");
var topQuery = "lotto";
var backQuery = encodeURIComponent("lotto");
var login_yn = "N";
var encodeType = "2";
var refCode = "";
var bucketType = "";
var name_check = "0";
var mobileDevice = "N";
var param_w = "tot";
var param_da = "SBC";
var paramCfg = "";
var param_cnucc = "";
var tpl_cfg = "";
var cnucc = "";
var usrIp = "175.198.89.213";
var isDetailTab = "N";
var schSort = "";
var existMobileTabYn = "N";
var width_over_620 = "Y";
var sPageLoadedmsTime =  143 ;
var isReleaseMode = '';
var isTotDebugMode = false;
var KAKAO_ACCOUNT_ID_CONNECTED = "N";
var displayInfo = {"SER":[{"code":"LOT","doc_count":1},{"code":"0NL","doc_count":9},{"code":"0SC","doc_count":2},{"code":"0LL","doc_count":2},{"code":"DIA","doc_count":1},{"code":"TWA","doc_count":1},{"code":"EM1","doc_count":0},{"code":"TWD","doc_count":5},{"code":"MS2","doc_count":1},{"code":"IVR","doc_count":3},{"code":"LB2","doc_count":1},{"code":"SNY","doc_count":8},{"code":"VOI","doc_count":6},{"code":"VOO","doc_count":10},{"code":"DNS","doc_count":4},{"code":"GG2","doc_count":1},{"code":"IIM","doc_count":20},{"code":"CLO","doc_count":1}],"SGR":[{"code":"NSJ","doc_count":0},{"code":"DCC","doc_count":0},{"code":"RTL","doc_count":10},{"code":"OUJ","doc_count":10},{"code":"1DR","doc_count":10},{"code":"1MV","doc_count":10},{"code":"RSJ","doc_count":0}],"SUI":[],"CUT":[{"code":"TGV","doc_count":0}]};
var usr4 = "NSJ0_LOT1_0NL9_0SC2_0LL2_DIA1_TWA1_EM10_TWD5_MS21_IVR3_LB21_SNY8_VOI6_VOO10_DNS4_GG21_IIM20_0GL0_DCC0_RTL10_OUJ10_1DR10_1MV10_RSJ0_CLO1";
var slCallType = "sync";
var pageLoadedTime = 0;
var startTime = new Date().getTime();
var sugLocCode = "";
var searchLog = {
uc: 0,
clickCount: 0,
dl: ""
};
var SEARCHLOGDOMAIN = "\/\/sl.search.daum.net";
var CNUCC_URL = "https:\/\/harm.search.daum.net\/v2\/api\/report-harm";
var ASUG_URL = "\/\/ninstant.search.daum.net\/suggest\/index.daum";
var AMADO_URL = "\/\/search1.daumcdn.net\/search\/statics\/common\/js\/fe\/amado-workspace\/pc\/3.0.1\/main.js";
var SF = {
phase: "prod",
userQueryParamW: "tot",
platform: "pc",
iam: {
clean: false,
geo: false,
login: false,
loginUrl: "https:\/\/logins.daum.net\/accounts\/loginform.do",
adult: false,
adultUrl: "https:\/\/logins.daum.net\/accounts\/loginform.do?service=adult_service\u0026url=https%3A%2F%2Fsearch.daum.net%2Fsearch%3FDA%3DSBC%26nil_suggest%3Dbtn%26q%3Dlotto%26realname_redirect%3D1%26w%3Dtot"
},
ua: {"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36","browser":{"name":"chrome","version":{"info":"151.0.0.0","major":151,"minor":0,"patch":0}},"device":"","os":{"name":"windows","version":{"info":"10","major":10,"minor":0,"patch":0}},"platform":"pc","app":{"isDaumapp":false,"isKakao":false,"version":{"info":"","major":0,"minor":0,"patch":0}}}
};
SF.ua.app.isApp = SF.ua.app.isDaumapp;
SF.ua.os[SF.ua.os.name] = true;
SF.ua.browser[SF.ua.browser.name] = true;
SF.loadModuleList = {"amcharts":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/amcharts.20190321202015.min.js","calendar":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/calendar/module.p.calendar.20210312112039.min.js","chart":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/chart.20200602182334.min.js","kakaosdk":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/kakaosdk.20230811110443.min.js","kakaotv":"//tv.kakao.com/player/script/sdk/player_api.min.js","ks":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/ks/module.p.ks.20221122154101.min.js","pagenavigation":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/pagenavigation/module.p.pagenavigation.20220705092744.min.js","v3":"//ssl.daumcdn.net/dmaps/map_js_init/v3.js","youtube":"//www.youtube.com/player_api"};
var SD = {};
var SG = {};
var C = {};
var T = {};
var SL = {
mkeyLog: function(){},
freelog: {
send: function(){}
},
dexposeLog: {
send: function(){}
},
xscrollLog: function(){}
};
var smartLog = function(){};
</script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/polyfill/p-legacy/1.4.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/logger/1.2.0/main.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/vendor/p/1.1.1/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/search-log/p/1.5.1/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/module/1.52.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/library/1.50.0/remoteEntry.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/runtime/1.48.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20260622160606/cubic.min.js?o=p" type="text/javascript"></script>
<script src="//t1.daumcdn.net/tiara/js/v1/tiara-1.2.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
(function(SF){
SF.tiaraTracker.setDefaultConfig();
})(window.SF || {});
</script>
</meta></head>
<body class="daum windows win chrome wide pc">
<script type="text/javascript">
SL.mkeyLog();
</script>
<nav class="d_direct" id="daumIndex">
<a class="link_direct" href="#daumBody">본문 바로가기</a>
<a class="link_direct" href="#daumGnb">메뉴 바로가기</a>
</nav>
<div id="saq" style="display:none">lotto</div>
<div class="sch_tab_tot" id="daumWrap">
<header id="daumHead">
<div class="d_head">
<h1 class="screen_out">다음</h1>
<h2 class="screen_out">검색</h2>
<div class="inner_header" id="innerHeader">
<form class="d_sch" id="daumSearch" method="get" name="search">
<fieldset class="fld_total">
<legend class="screen_out">검색폼</legend>
<input id="nil_suggest" name="nil_suggest" type="hidden" value="btn"/>
<input id="nil_ch" name="nil_ch" type="hidden" value=""/>
<input name="rtupcoll" type="hidden" value=""/>
<input name="w" type="hidden" value="tot"/>
<input name="m" type="hidden" value=""/>
<input id="f" name="f" type="hidden" value=""/>
<input name="lpp" type="hidden" value=""/>
<input name="DA" type="hidden" value="SBC"/>
<input name="sug" type="hidden" value=""/>
<input name="sq" type="hidden" value=""/>
<input name="o" type="hidden" value=""/>
<input name="sugo" type="hidden" value=""/>
<div class="box_searchbar">
<div class="inner_searchbar">
<a aria-label="Daum 메인페이지로 가기" class="link_service" data-target="_top" href="https://www.daum.net/" id="daumLogo" onclick='smartLog(this, "e=1&amp;dc=MLC", event);' target="_top" title="Daum 메인페이지로 가기">
<svg aria-hidden="true" fill="none" height="40" viewbox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_496_626)">
<mask height="24" id="mask0_496_626" maskunits="userSpaceOnUse" style="mask-type:alpha" width="24" x="10" y="8">
<path d="M22 14.36C25.1152 14.36 27.6352 17.072 27.5152 20.2136C27.4024 23.2016 24.8536 25.64 21.8632 25.64H17.9176C17.6536 25.64 17.4376 25.424 17.4376 25.16V14.84C17.4376 14.576 17.6536 14.36 17.9176 14.36H21.9976M22 8H12.4C11.6056 8 10.96 8.6456 10.96 9.44V30.56C10.96 31.3544 11.6056 32 12.4 32H22C28.6264 32 34 26.6264 34 20C34 13.3736 28.6264 8 22 8Z" fill="white"></path>
</mask>
<g mask="url(#mask0_496_626)">
<rect fill="url(#paint0_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
<rect fill="url(#paint1_radial_496_626)" height="24" transform="rotate(-180 33.9999 32)" width="23.04" x="33.9999" y="32"></rect>
<rect fill="url(#paint2_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
<rect fill="url(#paint3_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
<rect fill="url(#paint4_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
</g>
</g>
<defs>
<radialgradient cx="0" cy="0" gradienttransform="translate(11.32 8.48) rotate(47.9943) scale(27.6149 18.2643)" gradientunits="userSpaceOnUse" id="paint0_radial_496_626" r="1">
<stop stop-color="#1E84FF"></stop>
<stop offset="1" stop-color="#1E84FF"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(50.6799 32) rotate(90) scale(32.76 116.718)" gradientunits="userSpaceOnUse" id="paint1_radial_496_626" r="1">
<stop offset="0.0710642" stop-color="#F95F65"></stop>
<stop offset="0.255335" stop-color="#F95F97" stop-opacity="0.85"></stop>
<stop offset="0.488545" stop-color="#E952BE" stop-opacity="0.3"></stop>
<stop offset="0.64993" stop-color="#1E84FF" stop-opacity="0"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(31.12 11.96) rotate(133.452) scale(12.5628 13.3382)" gradientunits="userSpaceOnUse" id="paint2_radial_496_626" r="1">
<stop stop-color="#22BB64"></stop>
<stop offset="0.598459" stop-color="#22BBA4" stop-opacity="0.5"></stop>
<stop offset="1" stop-color="#61BACA" stop-opacity="0"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(34 21.92) rotate(-170.538) scale(11.6789 14.112)" gradientunits="userSpaceOnUse" id="paint3_radial_496_626" r="1">
<stop stop-color="#2FD800"></stop>
<stop offset="1" stop-color="#12EB1A" stop-opacity="0"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(29.32 29.72) rotate(-126.545) scale(12.6962 17.5254)" gradientunits="userSpaceOnUse" id="paint4_radial_496_626" r="1">
<stop stop-color="#FFC622"></stop>
<stop offset="0.524982" stop-color="#FFC622" stop-opacity="0.6"></stop>
<stop offset="1" stop-color="#FFC622" stop-opacity="0"></stop>
</radialgradient>
<clippath id="clip0_496_626">
<rect fill="white" height="24" transform="translate(10 8)" width="24"></rect>
</clippath>
</defs>
</svg>
</a>
<input autocomplete="off" class="tf_keyword" id="q" maxlength="255" name="q" title="검색어 입력" type="text" value="lotto"/>
<button class="btn_reset" id="btnResetHeader" onclick="smartLog(this, 'pg=1&amp;p=2&amp;r=1&amp;rc=1&amp;dc=SBC&amp;at=func', event);" title="검색어 지우기" type="button">
<span class="ico_ksg">입력삭제</span>
</button>
<button aria-label="가상키보드 열기" class="btn_vkey" id="VKIBtn" onclick="smartLog(this, 'pg=1&amp;p=1&amp;r=1&amp;rc=1&amp;dc=BFJ&amp;at=func', event);" title="가상키보드 열기" type="button">
<svg fill="none" height="28" width="28" xmlns="http://www.w3.org/2000/svg">
<rect height="15" rx="4" stroke="currentColor" stroke-width="2" width="24" x="2" y="6.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="9" x="9.5" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="16.5"></rect>
</svg>
</button>
<button aria-label="검색" class="btn_ksearch" id="daumBtnSearch" title="검색" type="submit">
<svg fill="currentColor" height="28" viewbox="0 0 28 28" width="28" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M12.5 4C17.1944 4 21 7.80558 21 12.5C21 14.501 20.3064 16.3389 19.1494 17.791C19.2295 17.8353 19.3051 17.891 19.373 17.959L24.373 22.959C24.7636 23.3495 24.7636 23.9825 24.373 24.373C23.9825 24.7636 23.3495 24.7636 22.959 24.373L17.959 19.373C17.891 19.3051 17.8353 19.2295 17.791 19.1494C16.3389 20.3064 14.501 21 12.5 21C7.80558 21 4 17.1944 4 12.5C4 7.80558 7.80558 4 12.5 4ZM12.5 6C8.91015 6 6 8.91015 6 12.5C6 16.0899 8.91015 19 12.5 19C16.0899 19 19 16.0899 19 12.5C19 8.91015 16.0899 6 12.5 6Z"></path>
</g>
</svg>
</button>
</div>
</div>
</fieldset>
<div class="box_suggest" id="daumSuggestTop"><div id="suggestBox"></div></div>
</form>
<div id="wrapMinidaum"></div>
</div>
<div id="daumGnb">
<div class="tab_dynamic tab_flex">
<ul class="list_tab">
<li class="on">
<span class="screen_out">선택된 항목</span>
<a class="tab_tit" href="?w=tot&amp;q=lotto&amp;DA=NTB" onclick="smartLog(this, 'pg=1&amp;r=1&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event);"><span class="inner_tab">통합</span></a>
</li>
<li class="">
<a class="tab_tit" href="?w=fusion&amp;nil_search=btn&amp;DA=NTB&amp;p=2&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=2&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
통합웹</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://www.melon.com/search/total/index.htm?q=lotto&amp;ref=W10060" onclick="smartLog(this, 'pg=1&amp;r=3&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
멜론뮤직<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=site&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;lpp=10&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=4&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
사이트</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=book&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=5&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
책</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://shoppinghow.kakao.com/search/lotto/&amp;srchhow=Cexpo" onclick="smartLog(this, 'pg=1&amp;r=6&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
쇼핑<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=vclip&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=7&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
동영상</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=news&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;cluster=y&amp;cluster_page=1&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=8&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
뉴스</span>
</a>
</li>
</ul>
<div class="more_dynamic more_search">
<button class="btn_tab" id="gnbToggleBtn" title="더보기" type="button">
<span class="ico_ksg">더보기/접기</span>
</button>
<ul class="list_more">
<li class="">
<a class="tab_tit" href="https://map.kakao.com/?from=total&amp;nil_suggest=btn&amp;tab=place&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=9&amp;p=2&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
지도<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=img&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=10&amp;p=2&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">

In [30]:
# 1236회 (2026.08.08 추첨)
# 당첨번호 [12, 18, 21, 29, 34, 38]
# 보너스 10
# times = soup.select_one('div.prize  span.f_red').text
prize = soup.find('div', class_='prize')
times = soup.find('span', class_='f_red').text
# date = soup.select_one('div.prize > span.date').text
date = soup.find('span', class_='date').text
# title1 = soup.select_one('div.prize > strong').text[-4:]
title1 = soup.find('strong').text[-4:]
# lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
lottonum = soup.find('div', class_='lottonum')
lotto_numbers = lottonum.find_all('span', class_='ball')[:-2]
# title2 = soup.select_one('div.lottonum span.screen_out').text
title2 = soup.find('span', class_='screen_out').text
# bonus_number = soup.select_one('div.lottonum > span.bg_ball1').text
bonus_number = soup.find('span', class_='bg_ball1').text
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2, bonus_number)

1236회 (2026.08.08 추첨)
기간 [12, 18, 21, 29, 34, 38]
선택된 항목 10

In [31]:
# 위의 select계열 함수를 find계열함수로 변경하여 구분해보기

### 3) 다음 뉴스 검색 리스트
```
no title href
0 타이틀1 http://~
1 타이틀2 http://~
2 타이틀3 http://~
```

In [6]:
# 방법 1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = f'https://search.daum.net/search?w=news&q={word}'
print(url)
response = requests.get(url)
print(response.status_code)
soup = BeautifulSoup(response.text, 'html.parser')

https://search.daum.net/search?w=news&q=비트코인
200

In [33]:
# 방법 2
from urllib.request import urlopen, Request
from urllib.parse import quote
word = quote('비트코인')
url = f'https://search.daum.net/search?w=news&q={word}'
print(url)
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
# request = Request(url, headers=headers)
request = Request(url)
request.add_header('User-Agent',
                  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response = urlopen(request)
print(response.status)
soup = BeautifulSoup(response, 'html.parser')
# soup

https://search.daum.net/search?w=news&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8
200

In [34]:
items_find_list = [] # 검색한 결과를 담을 dict 리스트
items_el = soup.select('div.item-title > strong.tit-g > a')
for idx, item in enumerate(items_el):
    # print(idx, item)
    items_find_list.append({'no':idx, 'title':item.text, 'link':item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list)

Empty DataFrame
Columns: []
Index: []

In [35]:
items_find_list = [] # 검색한 결과를 담을 2차원 리스트
items_el = soup.select('div.item-title > strong.tit-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs.get('href')])
pd.DataFrame(items_find_list, columns=['순번', '기사제목', '링크'])

Empty DataFrame
Columns: [순번, 기사제목, 링크]
Index: []

In [44]:
# 다음 뉴스 검색 함수(원하는 키워드, 원하는 페이지로)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def collect_list(keyword, page):
    'keyword로 해당 page에 검색한 결과 dict list return'
    # url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={keyword}&p={page}'
    url = 'https://search.daum.net/search?w=news'
    params = {'q': keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, 'html.parser')
    items_find_list = []
    items_el = soup.select('div.item-title > strong.tit-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({
            'no':(page-1)*10 + idx, 'title':item.text, 'link':item.attrs.get('href')
        })
    return items_find_list

In [45]:
collect_list('축구협회 성접대', 2)

[{'no': 10,
  'title': ' "대한축구협회 \'성접대\' 받은 심판 3명" 일본 발칵…한국 축구 또 \'망신\' ',
  'link': 'http://v.daum.net/v/20260807152410770'},
 {'no': 11,
  'title': " 축구협회 '성 접대' 의혹 터졌지만…'공소시효'가 변수 됐다 ",
  'link': 'http://v.daum.net/v/20260810140050538'},
 {'no': 12,
  'title': ' 민주당 "대한축구협회 성접대 명명백백 밝혀야…감사원·검찰도 책임 못 피해” ',
  'link': 'http://v.daum.net/v/20260812102310953'},
 {'no': 13,
  'title': ' 경찰, 축구협회 \'성 접대\' 수사 저울질…"공소시효 등 요건 파악 필요" ',
  'link': 'http://v.daum.net/v/20260810131047977'},
 {'no': 14,
  'title': ' ‘성접대 증거 고스란히 다 있었는데…’ 검찰, 2011년 축구협회 성접대에 “증거 불충분’ 무혐의 처분 ',
  'link': 'http://v.daum.net/v/20260808040253981'},
 {'no': 15,
  'title': ' 한정애 "축구협회 성접대, 공소시효 별개...해체 수준 대개혁 시급" ',
  'link': 'http://v.daum.net/v/20260813024312498'},
 {'no': 16,
  'title': ' \'국제 망신\' 대한축구협회 성 접대 파문에...일본도 일파만파 "대상 일본인 심판 4명 사실관계 확인 중" ',
  'link': 'http://v.daum.net/v/20260810154136339'},
 {'no': 17,
  'title': ' 축구협회 성접대 심판 7경기 무패…경찰, 수사 가능성 열어놨다 [세상&] ',
  'link': 'http://v.daum.net/v/20260810184654322'},
 {'no': 18,
  'title': " 실명까지 공개! '심판 마사지' 문건 후폭풍...韓 축구협회 성접대 의혹, 일본 4명 조사 착수 ",
  'link': 'http://v.daum.net/v/20260810165613539'},
 {'no': 19,
  'title': " '심판 마사지' 결재도 있었는데…황당한 검찰, 축구협회 성접대 의혹 '무혐의' 처분 논란 ",
  'link': 'http://v.daum.net/v/20260807225740698'}]

In [53]:
result = [] # 해당 키워드 원하는 페이지 수만큼 검색한 결과를 담을 변수 dict 리스트
pages = 3
for page in range(1, pages+1):
    print(f'== {page} 페이지 수집 중 ==')
    item_result = collect_list('서울19도', page)
    result.extend(item_result) # append가 아닌 / extend : 리스트에 묶는 것이 아닌 개별의 [],[]로 출력해줌
    time.sleep(2)
pd.DataFrame(result)

== 1 페이지 수집 중 ==
== 2 페이지 수집 중 ==
== 3 페이지 수집 중 ==

,no,title,link
0,0,"확 달라진 아침 공기, 열대야도 해소…내일 서울 19도까지 뚝",http://v.daum.net/v/20260811194444190
1,1,서울 새벽 기온 19도까지 내려간다…기록적 폭염 한풀 꺾이나,http://v.daum.net/v/20260811060243828
2,2,"40도 펄펄 끓다가...""갑자기 최저 19도"" 내일 서울 '초가을 날씨'",http://v.daum.net/v/20260811084455345
3,3,40도 넘더니 이제는 19도?…하루아침에 '초가을',http://v.daum.net/v/20260811105602699
4,4,"""8월에 웬 19도?""...'이날' 서울 아침 기온 뚝 떨어진다",http://v.daum.net/v/20260810135128216
5,5,“40도넘더니 이제는 19도?”…최저기온 ‘뚝’ 선선,http://v.daum.net/v/20260811010508306
6,6,"""40도 찍더니 19도까지 뚝?""…서울, 이번엔 초가을 날씨 온다",http://v.daum.net/v/20260811004652221
7,7,"""19도까지 떨어진다""…'입추' 아니라 원인은 따로?",http://v.daum.net/v/20260810155704096
8,8,'입추 매직' 통했다...내일 아침 최저기온 19도까지 '뚝',http://v.daum.net/v/20260810143448132
9,9,"""19도까지 떨어진다""...변수는 13호·15호 태풍",http://v.daum.net/v/20260810185737500
10,10,"아침엔 19도, 낮엔 34도…다시 찾아온 무더위에 소나기까지 [날씨]",http://v.daum.net/v/20260813063115560
11,11,“겉옷 챙길 생각에 행복합니다”…최저기온 19도까지 떨어진다는데,http://v.daum.net/v/20260810100600755
12,12,8월 11일 미리 보는 MBN 뉴스7,http://v.daum.net/v/20260811171441493
13,13,내일 아침 19도까지 '뚝'…한낮엔 34도 '폭염·열대야' 계속,http://v.daum.net/v/20260810091732458
14,14,"일부 당원 '장동혁 퇴진' 움직임에…국민의힘 ""張 지지 서명도 진행 중"" 등 [8...",http://v.daum.net/v/20260810170133803
15,15,열대야 드디어 멈추나…다음 주 수요일 아침 19도?,http://v.daum.net/v/20260808115907582
16,16,아침 최저 19도·낮 최고 34도…일교차 주의 [오늘의 날씨],http://v.daum.net/v/20260811050228230
17,17,"내일 아침 19도 선선, 낮 34도 무더위…도심·해안 일부 열대야(종합)",http://v.daum.net/v/20260810180402215
18,18,[날씨] 전국 대부분 폭염특보 해제‥내일부터 동해안 중심 비,http://v.daum.net/v/20260811211011191
19,19,[내일 날씨] 아침 최저 19도 '한풀 꺾인' 극한 폭염…낮엔 최고 34도,http://v.daum.net/v/20260810180107099
20,20,태풍 영향 동쪽에 비…내일 아침 서울 23도,http://v.daum.net/v/20260812140339901
21,21,수도권·남부 한낮 33도 '후텁지근'…동해안 최대 60㎜ 비 [오늘날씨],http://v.daum.net/v/20260812060239682
22,22,[날씨]서울 폭염특보 19일 만에 해제…전국 열대야주의보도 풀려,http://v.daum.net/v/20260811200225696
23,23,찜통더위 계속된다… 강원·경북 동해안 비 [오늘날씨],http://v.daum.net/v/20260812000218321
24,24,[오늘날씨] 동해안 곳곳 비...달라진 아침 공기 속 수도권 '폭염',http://v.daum.net/v/20260812000113268
25,25,[이슈날씨] 폭염과 열대야 주춤...비 소식 없는 남부권 가뭄 비상,http://v.daum.net/v/20260811213421784
26,26,동해안 비… 낮 최고기온 33도 [내일날씨],http://v.daum.net/v/20260811180127337
27,27,동해안 등에 비…폭염은 한풀 꺾여,http://v.daum.net/v/20260812120209447
28,28,"""17도까지 떨어진다""...'日 관통' 태풍 찬홈, 한국 영향은?",http://v.daum.net/v/20260811221337382
29,29,[오늘의 날씨] 아침 최저 17도까지 '뚝'…낮엔 33도 무더위,http://v.daum.net/v/20260812000222325

In [58]:
keywords = ['서울', '동대문']
pages = 3
result0 = [] # keyword[0] 1~pages 페이지까지 검색한 결과 dict list
result1 = [] # keyword[1] 1~pages페이지까지 검색한 결과 dict list
for i, keyword in enumerate(keywords):
    print(f'= = {i+1}번째 검색어 {keyword} 검색 결과 수집 ({pages}페이지) 중입니다 = =')
    for page in range(1, pages+1):
        if i==0:
            result0.extend(collect_list(keyword, page))
        else:
            result1.extend(collect_list(keyword, page))
        time.sleep(2)

= = 1번째 검색어 서울 검색 결과 수집 (3페이지) 중입니다 = =
= = 2번째 검색어 동대문 검색 결과 수집 (3페이지) 중입니다 = =

In [59]:
result0_df = pd.DataFrame(result0)
result1_df = pd.DataFrame(result1)
result1_df.sample()

,no,title,link
16,16,"롯데건설, 부천·동대문 홈플러스 개발로 PF 부담 7276억 덜어",http://v.daum.net/v/20260812145809766

In [61]:
result0_df.to_csv(f'data/ch14_{keywords[0]}.csv', index=False, encoding='cp949')
result1_df.to_csv(f'data/ch14_{keywords[1]}.csv', index=False, encoding='cp949')

### 4) User-Agent를 추가하여 크롤링
- request.get(url), urlopen(url)함수를 사용하면 크롤링이 막혀있는 사이트
- 방법2에서 User-Agent를 추가하여 크롤링

- https://www.melon.com/robots.txt에서 일부 경로는 User-Agent에 봇이 지정

In [64]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
melonResponse = requests.get(url)
print(melonResponse.status_code)
soup = BeautifulSoup(melonResponse.text, 'html.parser')
soup

406

In [65]:
# 방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
#melonResponse = urlopen(url) # HTTPError: HTTP Error 406: Not Acceptable

In [68]:
# User-Agent를 추가하여 방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
# melonpage = Request(url, headers=headers)
melonpage = Request(url)
melonpage.add_header('user-agent',
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
melonResponse = urlopen(melonpage)
print(melonResponse.status)
soup = BeautifulSoup(melonResponse, 'html.parser')
# soup

200

In [89]:
# User-Agent를 추가하여 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
headers = {'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
melonResponse = requests.get(url, headers=headers)
print(melonResponse.status_code)
soup = BeautifulSoup(melonResponse.text, 'html.parser')
# soup

200

In [103]:
# 1위 : LOVE ATTACK | RESCENE (리센느)의 url {}
# 순위, 곡명, 가수, 가수페이지
rank_els = soup.select('div.wrap.t_center > span.rank')[1:]
ranks = [rank.text for rank in rank_els]

title_els = soup.select('div.ellipsis.rank01 > span > a')
titles = [title.text for title in title_els]

singer_els = soup.select('span.checkEllipsis') # 40위, 90위 가수가 복수명
singers = [singer.text.replace('\xa0','') for singer in singer_els]

# link_els = soup.select('span.checkEllipsis > a')
# links = ['https://www.melon.com'+link.attrs.get('href') for link in link_els]
# len(links)

links = []
for singer_el in singer_els:
    # print(singer_el)
    singer_link = 'https://www.melon.com' + singer_el.find('a').attrs.get('href')
    links.append(singer_link)
len(ranks), len(titles), len(singers), len(links)

# for idx, (title, singer, link) in enumerate(zip(titles, singers, links)):
#     print("{}위. {} | {}".format(idx+1, title, singer, link))
melon_chat_list = []
for rank, title, singer, link in zip(ranks, titles, singers, links):
    # print(f'{rank}위 {title} | {singer}')
    melon_chat_list.append({
        '순위':rank,
        '곡명':title,
        '가수':singer,
        '가수페이지':link
    })
pd.DataFrame(melon_chat_list) # pd.options.display.max_rows(60)행이상은 중간이 생략

,순위,곡명,가수,가수페이지
0,1,LOVE ATTACK,RESCENE(리센느),https://www.melon.com/artist/detail.htm?artist...
1,2,갑자기,아이오아이(I.O.I),https://www.melon.com/artist/detail.htm?artist...
2,3,REDRED,CORTIS(코르티스),https://www.melon.com/artist/detail.htm?artist...
3,4,LEMONADE,aespa,https://www.melon.com/artist/detail.htm?artist...
4,5,Pretty Girl,RESCENE(리센느),https://www.melon.com/artist/detail.htm?artist...
...,...,...,...,...
95,96,BLACKHOLE,IVE(아이브),https://www.melon.com/artist/detail.htm?artist...
96,97,FOCUS,Hearts2Hearts(하츠투하츠),https://www.melon.com/artist/detail.htm?artist...
97,98,Soda Pop,"KPopDemonHuntersCast, DannyChung, SajaBoys, An...",https://www.melon.com/artist/detail.htm?artist...
98,99,OVERDRIVE,TWS(투어스),https://www.melon.com/artist/detail.htm?artist...
99,100,2.0,방탄소년단,https://www.melon.com/artist/detail.htm?artist...

### 5) 네이버 지식인 검색(open API 사용X)
- 특정 keyword를 특정 페이지 수만큼

In [111]:
# 방법1
from requests import get
from bs4 import BeautifulSoup
keyword = '동대문+필수코스'
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
print(url)
response = get(url)
print(response.status_code)
soup = BeautifulSoup(response.text, 'html.parser')

https://kin.naver.com/search/list.naver?query=동대문+필수코스
200

In [113]:
# 방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
from urllib.parse import quote
keyword = quote('동대문+필수코스')
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
print(url)
response = urlopen(url)
print(response.status)

https://kin.naver.com/search/list.naver?query=%EB%8F%99%EB%8C%80%EB%AC%B8%2B%ED%95%84%EC%88%98%EC%BD%94%EC%8A%A4
200

In [4]:
# keyword를 원하는 페이지 수만큼
from requests import get
from bs4 import BeautifulSoup
keyword = '동대문+추천'
pages = 5
items_list = [] # 크롤링한 데이터를 담을 list
for page in range(1, pages+1):
    url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
    print(url)
    # url = 'https://kin.naver.com/search/list.naver'
    # params = {'query':keyword, 'page':page}
    #response = get(url, params=params)
    response = get(url)
    # print(response.status_code)
    soup = BeautifulSoup(response.text, 'html.parser')
    # 글제목, link
    dt_els = soup.find_all('dt')
    for dt_el in dt_els:
        item = dt_el.find('a')
        items_list.append({
            'title':item.text,
            'link':item.attrs.get('href')
        })
df = pd.DataFrame(items_list)
df.head()

https://kin.naver.com/search/list.naver?query=동대문+추천&page=1
https://kin.naver.com/search/list.naver?query=동대문+추천&page=2
https://kin.naver.com/search/list.naver?query=동대문+추천&page=3
https://kin.naver.com/search/list.naver?query=동대문+추천&page=4
https://kin.naver.com/search/list.naver?query=동대문+추천&page=5

,title,link
0,동대문에서 하루 동안 여유롭게 즐길 수 있는....,https://kin.naver.com/qna/detail.naver?dirId=1...
1,중학생 여자아이들이 갈만한곳 서울시내 추....,https://kin.naver.com/qna/detail.naver?dirId=9...
2,"CGV 동대문 김기영관, 아트하우스 영화 추천 ....",https://kin.naver.com/qna/detail.naver?dirId=3...
3,동대문 부자재 상가 귀여운 아이템 추천해주....,https://kin.naver.com/qna/detail.naver?dirId=8...
4,동대문 흥인지문 근처 카페 추천,https://kin.naver.com/qna/detail.naver?dirId=1...

In [124]:
df.sample(10).sort_index()

,title,link
2,"CGV 동대문 김기영관, 아트하우스 영화 추천 ....",https://kin.naver.com/qna/detail.naver?dirId=3...
5,서울 명동&동대문 에서 놀곳 추천 받아여,https://kin.naver.com/qna/detail.naver?dirId=1...
8,"동묘,동대문 맛집 추천",https://kin.naver.com/qna/detail.naver?dirId=8...
15,광저우 시장 가을 의류?,https://kin.naver.com/qna/detail.naver?dirId=5...
16,동대문역사문화공원역 출퇴근 주말부부 아파....,https://kin.naver.com/qna/detail.naver?dirId=1...
19,8월2일오늘동대문새빛시장열까요?,https://kin.naver.com/qna/detail.naver?dirId=8...
29,동대문다이어트 병원 추천,https://kin.naver.com/qna/detail.naver?dirId=8...
32,동대문커텐 괜찮게 하는곳으로 추천해주세요,https://kin.naver.com/qna/detail.naver?dirId=1...
34,광희동 동대문 맛집 추천해주세,https://kin.naver.com/qna/detail.naver?dirId=7...
43,동대문 옷 사러갈 곳 추천 좀 해주세요 20대 ....,https://kin.naver.com/qna/detail.naver?dirId=5...

## 2.2 open API사용 : json 웹데이터 수집
### 1) 네이버 지식으로 검색 (open API사용 o)

- 네이버개발자 센터에서 애플리케이션을 등록(id, pw) => NAVER API HUB

In [126]:
%pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv, dotenv
Successfully installed dotenv-0.9.9 python-dotenv-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
# 환경변수를 쓰기 위한 패키지 : dotenv
from dotenv import load_dotenv
import os
load_dotenv(
    #dotenv_path='.env'
)
print(os.getenv('CLIENT_ID')[:3])
print(os.getenv('CLIENT_SECRET')[:3])

5Am
7Lv

In [ ]:
# 참고사항
# 방법 1 예시
import json
import os
import sys
import requests
import pandas as pd
from dotenv import load_dotenv
from requests import get
load_dotenv() # 환경 변수 load
client_id = os.getenv('NEW_CLIENT_ID')
client_secret = os.getenv('NEW_CLIENT_SECRET')
encText = "이사비 지원사업"
url = f"https://naverapihub.apigw.ntruss.com/search/v1/kin" # JSON 결과
params = {'query':encText, 'display':20 }
headers = {
    'X-NCP-APIGW-API-KEY-ID': client_id,
    'X-NCP-APIGW-API-KEY':client_secret
}
response = requests.get(url, params=params, headers=headers)

items = response.json()['items']# response를 json형태로 변환한것 중 'items' /  방법 1만 가능
items_list = []
for item in items:
    #print(item)
    title = item['title'].replace('<b>','').replace('</b>','')
    link = item['link']
    description = item['description'].replace('<b>', '').replace('</b>', '')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description']).sample()
# 참고사항

In [21]:
# 방법 1 네이버 개발자 센터
import json
import os
import sys
import urllib.parse
import urllib.request
import pandas as pd

client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')

encText = urllib.parse.quote("이사비 지원사업")
url = f"https://openapi.naver.com/v1/search/image?query={encText}&display=100"

headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
request = urllib.request.Request(url, headers=headers)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8')[:30])
else:
    print("Error Code:" + rescode)
    
data = json.loads(response_body) # 문자를 json형태로 변환
print('data의 응답들 :', data.keys())
print('검색결과 개수 :', len(data['items']))

items = data['items']
items_list = []
for item in items:
    title = item['title'].replace('<b>','').replace('</b>','')
    link = item['link']
    sizeheight = item['sizeheight']
    sizewidth = item['sizewidth']
    
    items_list.append({
        '제목':item.get('title'),
        '링크':item.get('link'),
        '썸네일':item.get('thumbnail'),
        '세로 size':item.get('sizeheight'),
        '가로 size':item.get('sizewidth')
    })
pd.DataFrame(items_list)

{
	"lastBuildDate":"Thu, 13 Au
data의 응답들 : dict_keys(['lastBuildDate', 'total', 'start', 'display', 'items'])
검색결과 개수 : 100

,제목,링크,썸네일,세로 size,가로 size
0,2024년 청년 이사비 및 중개보수비 지원사업 | 일반공지 | 중부소식방 | 중부광...,https://www.joongbu.ac.kr/upload/editor/images...,https://search.pstatic.net/sunny/?type=b150&sr...,920,653
1,서울 청년 이사비 최대 '40만 원' 지원…'중개 수수료'까지 확대,http://imgnews.naver.net/image/5003/2022/10/10...,https://search.pstatic.net/common/?type=b150&s...,505,540
2,"서울시, 청년 이사비 지원사업 문턱 낮춘다…최대 40만원 지원",http://imgnews.naver.net/image/029/2023/05/08/...,https://search.pstatic.net/common/?type=b150&s...,441,540
3,"영주시, 경북도 최초 청년 이사비 최대 50만원 지원",http://imgnews.naver.net/image/382/2023/05/09/...,https://search.pstatic.net/common/?type=b150&s...,600,600
4,"서울시, 청년 부동산중개료·이사비 최대 40만원 지원",http://imgnews.naver.net/image/5464/2024/08/12...,https://search.pstatic.net/common/?type=b150&s...,430,600
...,...,...,...,...,...
95,"장수군, '이·미용·목욕비 지원사업' 바우처 카드 도입",http://imgnews.naver.net/image/5268/2023/01/10...,https://search.pstatic.net/common/?type=b150&s...,439,658
96,"""이사비 줄테니 지방근무자 본사 출근하라""…쿠팡, 일방통행式 소셜사업 종료에 구설수",http://imgnews.naver.net/image/366/2017/02/08/...,https://search.pstatic.net/common/?type=b150&s...,341,478
97,"최대 40만 원, 서울시 청년이라면 이사비 받으세요",https://img1.daumcdn.net/thumb/R1280x0.fpng/?f...,https://search.pstatic.net/sunny/?type=b150&sr...,710,1280
98,영덕군 - 소기업 소상공인 방역물품비 지원사업 안내 | 공지사항 소기업 소상공인 방...,https://www.yd.go.kr/wp-content/uploads/kboard...,https://search.pstatic.net/sunny/?type=b150&sr...,901,1647
99,2021 에쓰-오일 '청년 푸드트럭 유류비 지원사업' 모집,http://imgnews.naver.net/image/5294/2021/04/13...,https://search.pstatic.net/common/?type=b150&s...,428,600

In [141]:
# 방법 2
import json
import os
import sys
import urllib.request
import pandas
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText = urllib.parse.quote("이사비+지원사업")
url = f"https://openapi.naver.com/v1/search/kin.json?query={encText}&sort.text" # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
# request = urllib.request.Request(url)
# request.add_header("X-Naver-Client-Id",client_id)
# request.add_header("X-Naver-Client-Secret",client_secret)
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
request = urllib.request.Request(url, headers=headers)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8')[:30])
else:
    print("Error Code:" + rescode)
    
data = json.loads(response_body) # 문자를 json형태로 변환
print('data의 응답들 :', data.keys())
print('검색결과 개수 :', len(data['items']))

items = data['items']
items_list = []
for item in items:
    #print(item)
    title = item['title'].replace('<b>','').replace('</b>','')
    link = item['link']
    description = item['description'].replace('<b>', '').replace('</b>', '')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description'])

{
	"lastBuildDate":"Thu, 13 Au
data의 응답들 : dict_keys(['lastBuildDate', 'total', 'start', 'display', 'items'])
검색결과 개수 : 10

,title,link,description
0,주거취약계층 이사비용지원 사업,https://kin.naver.com/qna/detail.naver?dirId=1...,"이사비 지원은 보통 거주하시던 곳의 유형에 따라 결정되는데, 국토부의 비정상거처 거..."
1,주거취약계층 이사비용지원 사업,https://kin.naver.com/qna/detail.naver?dirId=1...,자세한 내용은 마이홈포털 비정상거처거주자 이사비지원 페이지에서 확인하실 수 있어요....
2,주거취약계층 이사비지원사업 신청대상과 구비서류 및 지원....,https://kin.naver.com/qna/detail.naver?dirId=6...,주거취약계층 이사비지원사업 신청대상과 구비서류 및 지원내용이 어떻게 되나요? 1. ...
3,온용산 이사비 지원 사업이란?,https://kin.naver.com/qna/detail.naver?dirId=6...,온용산 이사비 지원 사업이란? ㅇ 지원대상 : 용산구(관내 전입 포함)에 전입한 생...
4,청년 부동산 중개보수 및 이사비 지원사업 제출서류,https://kin.naver.com/qna/detail.naver?dirId=4...,해당 지원사업을 신청하려고 하는데 부동산에서 부가세 빼고 그냥 이체하거나 부가세 포...
5,주거취약계층 이사비용지원 사업,https://kin.naver.com/qna/detail.naver?dirId=1...,그리고 쿠팡으로 세탁기 샀어요 주거취약계층 이사비용지원 신청과 서류 안내 질문자님 ...
6,청년 부동산 중개보수 및 이사비 지원사업 제출서류,https://kin.naver.com/qna/detail.naver?dirId=4...,해당 지원사업을 신청하려고 하는데 부동산에서 부가세 빼고 그냥 이체하거나 부가세 포...
7,서울시 부동산 중개보수 및 이사비 지원사업 서류 통과 후 ....,https://kin.naver.com/qna/detail.naver?dirId=6...,금번 2026 서울시 부동산 중개보수 및 이사비 지원사업 서류 통과 후 8월 최종 ...
8,2026년 상반기 청년 부동산 중개보수 및 이사비 지원사업,https://kin.naver.com/qna/detail.naver?dirId=6...,"작년과 올해 진행 일정을 보면, 이 사업은 심사 기간이 비교적 긴 편입니다. 1.2..."
9,청년몽땅정보통 이사비 지원 사업,https://kin.naver.com/qna/detail.naver?dirId=6...,김연광 행정사 입니다.(대한행정사회 연수원 교수) 질문자님이 문의한 내용은 &lt;...

### NAVER API HUB

In [16]:
# 방법 1 예시
import json
import os
import sys
import requests
import pandas as pd
from dotenv import load_dotenv
from requests import get
load_dotenv() # 환경 변수 load
client_id = os.getenv('NEW_CLIENT_ID')
client_secret = os.getenv('NEW_CLIENT_SECRET')
encText = "이사비 지원사업"
url = f"https://naverapihub.apigw.ntruss.com/search/v1/kin" # JSON 결과
params = {'query':encText, 'display':20 }
headers = {
    'X-NCP-APIGW-API-KEY-ID': client_id,
    'X-NCP-APIGW-API-KEY':client_secret
}
response = requests.get(url, params=params, headers=headers)

items = response.json()['items']# response를 json형태로 변환한것 중 'items' /  방법 1만 가능
items_list = []
for item in items:
    #print(item)
    title = item['title'].replace('<b>','').replace('</b>','')
    link = item['link']
    description = item['description'].replace('<b>', '').replace('</b>', '')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description']).sample()

,title,link,description
6,주거취약계층 이사비용지원 사업,https://kin.naver.com/qna/detail.naver?dirId=1...,그리고 쿠팡으로 세탁기 샀어요 주거취약계층 이사비용지원 신청과 서류 안내 질문자님 ...

In [23]:
# df.to_csv('data/img_list.csv', encoding='cp949', index=False)

In [24]:
# df에 있는 이미지 로컬에 저장하기
# print(df.loc[0, '링크']) # 메일_00_청바지.jpg
# print(df.loc[0, '썸네일']) # 썸네일_01_청바지.jpg

In [28]:
def save_image(attr, idx, link, query):
    'link의 이미지를 image/attr_idx_query.확장자로 local에 저장'
    import requests
    file_extension = link.split('.')[-1]
    quote_index = file_extension.find('?') # 확장자 뒤에 ?가 있는 위치(?가 없으면 -1)
    if quote_index != -1:
        file_extension = file_extension[:quote_index] # 물음표앞까지만 확장자로
    img = requests.get(link).content # link요청을 바이너리
    with open(f'image/{attr}_{idx:02}_{query}.{file_extension}', 'wb') as f:
        f.write(img) # 파일 저장
save_image('메인', 0, df.loc[0,'링크'], '청바지')

NameError: name 'df' is not defined

In [ ]:
# 강사님 깃허브
# https://github.com/4aix/ai