In [1]:
from IPython.display import display, HTML

display(HTML("""
<style>

/* =========================
전체 레이아웃
========================= */

div.container{
    width:85% !important;
}

div.cell.code_cell.rendered{
    width:100%;
}

div.input_prompt{
    padding:0;
}

div.prompt{
    min-width:70px;
}

div#toc-wrapper{
    padding-top:120px;
}

table.dataframe{
    font-size:12px;
}

/* =========================
   코드 입력창
========================= */

div.CodeMirror{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
    line-height:1.6;
}

/* =========================
   입력 셀
========================= */

div.input{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   코드 출력
========================= */

div.output{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   Markdown 전체
========================= */

.rendered_html{
    font-family:"마루 부리OTF 중간" !important;
    font-size:18px !important;
    line-height:1.8;
}

/* 제목 */

.rendered_html h1,
.rendered_html h2,
.rendered_html h3,
.rendered_html h4,
.rendered_html h5,
.rendered_html h6{
    font-family:"마루 부리OTF 조금굵은" !important;
}

/* 본문 */

.rendered_html p{
    font-family:"마루 부리OTF 중간" !important;
}

/* 리스트 */

.rendered_html li{
    font-family:"마루 부리OTF 중간" !important;
    padding:5px;
}

/* 인용 */

.rendered_html blockquote{
    font-family:"마루 부리OTF 중간" !important;
}

/* 표 */

.rendered_html table{
    font-family:"마루 부리OTF 중간" !important;
}

/* 코드 블록 */

.rendered_html pre,
.rendered_html code{
    font-family:"Consolas" !important;
    font-size:12pt !important;
}

</style>
"""))

In [2]:
import pandas as pd

# 데이터 수집 및 확인

In [4]:
# 데이터 수집 및 확인
store = pd.read_csv("./data/독립변수1_서울시 상권분석서비스(점포-상권)_2025년.csv", encoding="cp949")
change = pd.read_csv("./data/독립변수2_서울시 상권분석서비스(상권변화지표-상권).csv", encoding="cp949")
sales = pd.read_csv("./data/독립변수3_서울시 상권분석서비스(추정매출-상권)_2025년.csv", encoding="cp949")
sales_bg = pd.read_csv("./data/독립변수3_선택_서울시 상권분석서비스(추정매출-상권배후지)_2025년.csv", encoding="cp949")

# 데이터 크기 확인
print("점포-상권 :", store.shape)
print("상권변화지표-상권 :", change.shape)
print("추정매출-상권 :", sales.shape)
print("추정매출-상권배후지 :", sales_bg.shape)

점포-상권 : (304775, 14)
상권변화지표-상권 : (36300, 11)
추정매출-상권 : (85732, 55)
추정매출-상권배후지 : (147035, 55)

In [27]:
# 데이터 확인
display(store.head(1))          # 점포-상권
display(change.head(1))      # 상권변화지표-상권
display(sales.head(1))          # 추정매출-상권
display(sales_bg.head(1))   # 추정매출-상권배후지

,stdr_yyqu_cd,trdar_se_cd,trdar_se_cd_nm,trdar_cd,trdar_cd_nm,svc_induty_cd,svc_induty_cd_nm,stor_co,similr_induty_stor_co,opbiz_rt,opbiz_stor_co,clsbiz_rt,clsbiz_stor_co,frc_stor_co
0,20251,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,12,13,0,0,8,1,1

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균
0,20262,U,관광특구,3001496,강남 마이스 관광특구,HH,정체,131,68,118,54

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_금액,...,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수
0,20251,U,관광특구,3001491,이태원 관광특구,CS300015,가방,1569075360,7398,1271375387,...,1736,35,2010,5330,0,539,752,990,1393,3666

,stdr_yyqu_cd,trdar_se_cd,trdar_se_cd_nm,trdar_cd,trdar_cd_nm,svc_induty_cd,svc_induty_cd_nm,thsmon_selng_amt,thsmon_selng_co,mdwk_selng_amt,...,tmzon_17_21_selng_co,tmzon_21_24_selng_co,ml_selng_co,fml_selng_co,agrde_10_selng_co,agrde_20_selng_co,agrde_30_selng_co,agrde_40_selng_co,agrde_50_selng_co,agrde_60_above_selng_co
0,20251,A,골목상권,3110001,이북5도청사,CS100001,한식음식점,927909980,20123,601778079,...,6766,523,11536,6041,237,815,1967,3359,4670,6531

# 컬럼명 확인

In [8]:
# 컬럼명 확인
print("=== 점포-상권 ===")
print(store.columns.tolist())

print("\n=== 상권변화지표-상권 ===")
print(change.columns.tolist())

print("\n=== 추정매출-상권 ===")
print(sales.columns.tolist())

print("\n=== 추정매출-상권배후지 ===")
print(sales_bg.columns.tolist())

=== 점포-상권 ===
['stdr_yyqu_cd', 'trdar_se_cd', 'trdar_se_cd_nm', 'trdar_cd', 'trdar_cd_nm', 'svc_induty_cd', 'svc_induty_cd_nm', 'stor_co', 'similr_induty_stor_co', 'opbiz_rt', 'opbiz_stor_co', 'clsbiz_rt', 'clsbiz_stor_co', 'frc_stor_co']

=== 상권변화지표-상권 ===
['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '상권_변화_지표', '상권_변화_지표_명', '운영_영업_개월_평균', '폐업_영업_개월_평균', '서울_운영_영업_개월_평균', '서울_폐업_영업_개월_평균']

=== 추정매출-상권 ===
['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액', '당월_매출_건수', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액', '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액', '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액', '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액', '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수', '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수', '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수', '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수', '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수', '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수', '연령대_50_매출_건수', '연령대_60_이상_매출_건수']

=== 추정매출-상권배후지 ===
['stdr_yyqu_cd', 'trdar_se_cd', 'trdar_se_cd_nm', 'trdar_cd', 'trdar_cd_nm', 'svc_induty_cd', 'svc_induty_cd_nm', 'thsmon_selng_amt', 'thsmon_selng_co', 'mdwk_selng_amt', 'wkend_selng_amt', 'mon_selng_amt', 'tues_selng_amt', 'wed_selng_amt', 'thur_selng_amt', 'fri_selng_amt', 'sat_selng_amt', 'sun_selng_amt', 'tmzon_00_06_selng_amt', 'tmzon_06_11_selng_amt', 'tmzon_11_14_selng_amt', 'tmzon_14_17_selng_amt', 'tmzon_17_21_selng_amt', 'tmzon_21_24_selng_amt', 'ml_selng_amt', 'fml_selng_amt', 'agrde_10_selng_amt', 'agrde_20_selng_amt', 'agrde_30_selng_amt', 'agrde_40_selng_amt', 'agrde_50_selng_amt', 'agrde_60_above_selng_amt', 'mdwk_selng_co', 'wkend_selng_co', 'mon_selng_co', 'tues_selng_co', 'wed_selng_co', 'thur_selng_co', 'fri_selng_co', 'sat_selng_co', 'sun_selng_co', 'tmzon_00_06_selng_co', 'tmzon_06_11_selng_co', 'tmzon_11_14_selng_co', 'tmzon_14_17_selng_co', 'tmzon_17_21_selng_co', 'tmzon_21_24_selng_co', 'ml_selng_co', 'fml_selng_co', 'agrde_10_selng_co', 'agrde_20_selng_co', 'agrde_30_selng_co', 'agrde_40_selng_co', 'agrde_50_selng_co', 'agrde_60_above_selng_co']

# 데이터 타입 확인

In [10]:
# 데이터 타입 확인
store.info()
change.info()
sales.info()
sales_bg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304775 entries, 0 to 304774
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   stdr_yyqu_cd           304775 non-null  int64
 1   trdar_se_cd            304775 non-null  object
 2   trdar_se_cd_nm         304775 non-null  object
 3   trdar_cd               304775 non-null  int64
 4   trdar_cd_nm            304775 non-null  object
 5   svc_induty_cd          304775 non-null  object
 6   svc_induty_cd_nm       304775 non-null  object
 7   stor_co                304775 non-null  int64
 8   similr_induty_stor_co  304775 non-null  int64
 9   opbiz_rt               304775 non-null  int64
 10  opbiz_stor_co          304775 non-null  int64
 11  clsbiz_rt              304775 non-null  int64
 12  clsbiz_stor_co         304775 non-null  int64
 13  frc_stor_co            304775 non-null  int64
dtypes: int64(9), object(5)
memory usage: 32.6+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36300 entries, 0 to 36299
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   기준_년분기_코드       36300 non-null  int64
 1   상권_구분_코드        36300 non-null  object
 2   상권_구분_코드_명      36300 non-null  object
 3   상권_코드           36300 non-null  int64
 4   상권_코드_명         36300 non-null  object
 5   상권_변화_지표        36300 non-null  object
 6   상권_변화_지표_명      36300 non-null  object
 7   운영_영업_개월_평균     36300 non-null  int64
 8   폐업_영업_개월_평균     36300 non-null  int64
 9   서울_운영_영업_개월_평균  36300 non-null  int64
 10  서울_폐업_영업_개월_평균  36300 non-null  int64
dtypes: int64(6), object(5)
memory usage: 3.0+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85732 entries, 0 to 85731
Data columns (total 55 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   기준_년분기_코드        85732 non-null  int64
 1   상권_구분_코드         85732 non-null  object
 2   상권_구분_코드_명       85732 non-null  object
 3   상권_코드            85732 non-null  int64
 4   상권_코드_명          85732 non-null  object
 5   서비스_업종_코드        85732 non-null  object
 6   서비스_업종_코드_명      85732 non-null  object
 7   당월_매출_금액         85732 non-null  int64
 8   당월_매출_건수         85732 non-null  int64
 9   주중_매출_금액         85732 non-null  int64
 10  주말_매출_금액         85732 non-null  int64
 11  월요일_매출_금액        85732 non-null  int64
 12  화요일_매출_금액        85732 non-null  int64
 13  수요일_매출_금액        85732 non-null  int64
 14  목요일_매출_금액        85732 non-null  int64
 15  금요일_매출_금액        85732 non-null  int64
 16  토요일_매출_금액        85732 non-null  int64
 17  일요일_매출_금액        85732 non-null  int64
 18  시간대_00~06_매출_금액  85732 non-null  int64
 19  시간대_06~11_매출_금액  85732 non-null  int64
 20  시간대_11~14_매출_금액  85732 non-null  int64
 21  시간대_14~17_매출_금액  85732 non-null  int64
 22  시간대_17~21_매출_금액  85732 non-null  int64
 23  시간대_21~24_매출_금액  85732 non-null  int64
 24  남성_매출_금액         85732 non-null  int64
 25  여성_매출_금액         85732 non-null  int64
 26  연령대_10_매출_금액     85732 non-null  int64
 27  연령대_20_매출_금액     85732 non-null  int64
 28  연령대_30_매출_금액     85732 non-null  int64
 29  연령대_40_매출_금액     85732 non-null  int64
 30  연령대_50_매출_금액     85732 non-null  int64
 31  연령대_60_이상_매출_금액  85732 non-null  int64
 32  주중_매출_건수         85732 non-null  int64
 33  주말_매출_건수         85732 non-null  int64
 34  월요일_매출_건수        85732 non-null  int64
 35  화요일_매출_건수        85732 non-null  int64
 36  수요일_매출_건수        85732 non-null  int64
 37  목요일_매출_건수        85732 non-null  int64
 38  금요일_매출_건수        85732 non-null  int64
 39  토요일_매출_건수        85732 non-null  int64
 40  일요일_매출_건수        85732 non-null  int64
 41  시간대_건수~06_매출_건수  85732 non-null  int64
 42  시간대_건수~11_매출_건수  85732 non-null  int64
 43  시간대_건수~14_매출_건수  85732 non-null  int64
 44  시간대_건수~17_매출_건수  85732 non-null  int64
 45  시간대_건수~21_매출_건수  85732 non-null  int64
 46  시간대_건수~24_매출_건수  85732 non-null  int64
 47  남성_매출_건수         85732 non-null  int64
 48  여성_매출_건수         85732 non-null  int64
 49  연령대_10_매출_건수     85732 non-null  int64
 50  연령대_20_매출_건수     85732 non-null  int64
 51  연령대_30_매출_건수     85732 non-null  int64
 52  연령대_40_매출_건수     85732 non-null  int64
 53  연령대_50_매출_건수     85732 non-null  int64
 54  연령대_60_이상_매출_건수  85732 non-null  int64
dtypes: int64(50), object(5)
memory usage: 36.0+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147035 entries, 0 to 147034
Data columns (total 55 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   stdr_yyqu_cd              147035 non-null  int64
 1   trdar_se_cd               147035 non-null  object
 2   trdar_se_cd_nm            147035 non-null  object
 3   trdar_cd                  147035 non-null  int64
 4   trdar_cd_nm               147035 non-null  object
 5   svc_induty_cd             147035 non-null  object
 6   svc_induty_cd_nm          147035 non-null  object
 7   thsmon_selng_amt          147035 non-null  int64
 8   thsmon_selng_co           147035 non-null  int64
 9   mdwk_selng_amt            147035 non-null  int64
 10  wkend_selng_amt           147035 non-null  int64
 11  mon_selng_amt             147035 non-null  int64
 12  tues_selng_amt            147035 non-null  int64
 13  wed_selng_amt             147035 non-null  int64
 14  thur_selng_amt            147035 non-null  int64
 15  fri_selng_amt             147035 non-null  int64
 16  sat_selng_amt             147035 non-null  int64
 17  sun_selng_amt             147035 non-null  int64
 18  tmzon_00_06_selng_amt     147035 non-null  int64
 19  tmzon_06_11_selng_amt     147035 non-null  int64
 20  tmzon_11_14_selng_amt     147035 non-null  int64
 21  tmzon_14_17_selng_amt     147035 non-null  int64
 22  tmzon_17_21_selng_amt     147035 non-null  int64
 23  tmzon_21_24_selng_amt     147035 non-null  int64
 24  ml_selng_amt              147035 non-null  int64
 25  fml_selng_amt             147035 non-null  int64
 26  agrde_10_selng_amt        147035 non-null  int64
 27  agrde_20_selng_amt        147035 non-null  int64
 28  agrde_30_selng_amt        147035 non-null  int64
 29  agrde_40_selng_amt        147035 non-null  int64
 30  agrde_50_selng_amt        147035 non-null  int64
 31  agrde_60_above_selng_amt  147035 non-null  int64
 32  mdwk_selng_co             147035 non-null  int64
 33  wkend_selng_co            147035 non-null  int64
 34  mon_selng_co              147035 non-null  int64
 35  tues_selng_co             147035 non-null  int64
 36  wed_selng_co              147035 non-null  int64
 37  thur_selng_co             147035 non-null  int64
 38  fri_selng_co              147035 non-null  int64
 39  sat_selng_co              147035 non-null  int64
 40  sun_selng_co              147035 non-null  int64
 41  tmzon_00_06_selng_co      147035 non-null  int64
 42  tmzon_06_11_selng_co      147035 non-null  int64
 43  tmzon_11_14_selng_co      147035 non-null  int64
 44  tmzon_14_17_selng_co      147035 non-null  int64
 45  tmzon_17_21_selng_co      147035 non-null  int64
 46  tmzon_21_24_selng_co      147035 non-null  int64
 47  ml_selng_co               147035 non-null  int64
 48  fml_selng_co              147035 non-null  int64
 49  agrde_10_selng_co         147035 non-null  int64
 50  agrde_20_selng_co         147035 non-null  int64
 51  agrde_30_selng_co         147035 non-null  int64
 52  agrde_40_selng_co         147035 non-null  int64
 53  agrde_50_selng_co         147035 non-null  int64
 54  agrde_60_above_selng_co   147035 non-null  int64
dtypes: int64(50), object(5)
memory usage: 61.7+ MB

# 결측치 확인

In [11]:
# 결측치 확인
def check_missing(df):
    result = pd.DataFrame({
        "결측치": df.isnull().sum(),
        "결측률(%)": (df.isnull().mean() * 100).round(2)
    })
    return result[result["결측치"] > 0]

display(check_missing(store))
display(check_missing(change))
display(check_missing(sales))
display(check_missing(sales_bg))

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

# 중복 데이터 확인

In [12]:
# 중복 데이터 확인
print("점포-상권 중복:", store.duplicated().sum())
print("상권변화지표 중복:", change.duplicated().sum())
print("추정매출-상권 중복:", sales.duplicated().sum())
print("추정매출-상권배후지 중복:", sales_bg.duplicated().sum())

점포-상권 중복: 0
상권변화지표 중복: 0
추정매출-상권 중복: 0
추정매출-상권배후지 중복: 0

# 기초통계 확인

## describe() 각 행의 의미
- count : 컬럼마다 다르면 그 컬럼에 결측치가 있다는 의미.
- mean vs 50%(중앙값) : 둘이 크게 다르면 값이 한쪽으로 치우침(극단값 존재)
- min/max : 불가능한 값, 극단적인 이상치 확인
- 25%/75% : 대부분의 데이터가 실제로 어디에 모여있는지
- std : 값이 얼마나 들쭉날짝한지

### 빠른 체크
- mean ≈ 50% : 고른 분포, 평균 써도 OK
- mean ≫ 50% : 큰 값 쪽으로 치우침, 중앙값 쓰거나 로그 변환 고려
- mean > 75% : 극단값 영향이 매우 큼
- 25%~75%가 모두 0 : 대부분이 0인 데이터
- std가 mean보다 훨씬 큼	: 값이 매우 들쭉날쭉
- max가 75%의 수백~수천 배 :	이상치 확인 필요
- min/max가 현실적으로 불가능 :	오류 가능성

In [18]:
# 기초통계 확인
display(store.describe())        # 점포-상권
display(change.describe())    # 상권변화지표-상권
display(sales.describe())        # 추정매출-상권
display(sales_bg.describe())  # 추정매출-상권배후지

,stdr_yyqu_cd,trdar_cd,stor_co,similr_induty_stor_co,opbiz_rt,opbiz_stor_co,clsbiz_rt,clsbiz_stor_co,frc_stor_co
count,"304,775.00","304,775.00","304,775.00","304,775.00","304,775.00","304,775.00","304,775.00","304,775.00","304,775.00"
mean,"20,252.50","3,114,804.73",6.26,6.79,1.99,0.13,2.33,0.17,0.53
std,1.12,"11,759.37",51.47,51.86,10.09,0.60,11.71,1.26,2.39
min,"20,251.00","3,001,491.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,"20,251.00","3,110,437.00",1.00,1.00,0.00,0.00,0.00,0.00,0.00
50%,"20,252.00","3,110,871.00",2.00,2.00,0.00,0.00,0.00,0.00,0.00
75%,"20,253.00","3,120,138.00",5.00,5.00,0.00,0.00,0.00,0.00,0.00
max,"20,254.00","3,130,327.00","11,433.00","11,444.00",200.00,28.00,450.00,291.00,151.00

,기준_년분기_코드,상권_코드,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균
count,"36,300.00","36,300.00","36,300.00","36,300.00","36,300.00","36,300.00"
mean,"20,235.14","3,115,221.90",109.67,52.66,103.95,51.36
std,15.89,"10,318.67",26.00,10.70,7.40,1.43
min,"20,211.00","3,001,491.00",3.00,20.00,94.00,49.00
25%,"20,222.00","3,110,407.00",94.00,47.00,98.00,50.00
50%,"20,233.50","3,110,819.50",106.00,51.00,101.50,51.00
75%,"20,251.00","3,120,142.00",121.00,56.00,111.00,52.00
max,"20,262.00","3,130,327.00",351.00,226.00,118.00,54.00

,기준_년분기_코드,상권_코드,당월_매출_금액,당월_매출_건수,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,...,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수
count,"85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00",...,"85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00","85,732.00"
mean,"20,252.50","3,115,455.87","1,080,789,331.95","35,608.20","815,691,541.68","265,097,790.27","158,518,803.22","159,723,146.20","159,939,438.17","158,721,025.17",...,"8,973.50","2,677.53","17,487.32","16,492.72",395.81,"5,330.24","7,935.12","6,611.03","6,549.41","7,158.44"
std,1.12,"14,157.81","9,191,794,782.76","173,232.72","6,192,213,546.09","3,329,908,680.33","1,180,791,884.52","1,196,964,964.92","1,236,434,075.36","1,225,512,158.82",...,"44,427.40","11,415.30","83,683.68","86,062.68","2,431.12","27,323.89","38,160.54","31,597.75","33,405.50","59,134.84"
min,"20,251.00","3,001,491.00",31.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,"20,252.00","3,110,534.00","45,838,107.00",770.00,"33,776,424.00","7,125,408.50","5,121,054.75","5,289,032.00","5,616,288.25","5,624,929.25",...,192.00,0.00,345.00,301.00,0.00,24.00,89.00,134.00,148.00,112.00
50%,"20,252.00","3,111,072.50","172,136,309.00","4,124.00","127,997,622.50","35,850,116.50","22,665,597.50","23,322,686.00","23,977,429.50","23,916,224.00",...,"1,107.50",50.00,"2,015.00","1,749.50",7.00,285.00,649.00,751.00,852.00,723.00
75%,"20,253.00","3,120,183.00","615,962,477.25","21,572.25","466,948,320.25","137,537,196.00","88,720,936.50","89,508,292.25","91,166,305.00","89,672,235.50",...,"5,739.25",958.25,"10,507.00","9,816.25",114.00,"2,189.25","4,038.00","3,884.00","4,286.00","3,927.25"
max,"20,254.00","3,130,327.00","1,148,993,825,259.00","13,299,388.00","702,979,967,421.00","446,013,857,838.00","112,212,457,917.00","119,179,438,672.00","144,547,315,928.00","145,202,697,089.00",...,"4,399,314.00","520,822.00","7,231,893.00","5,110,243.00","179,680.00","1,599,813.00","2,592,933.00","1,979,297.00","2,381,030.00","4,965,867.00"

,stdr_yyqu_cd,trdar_cd,thsmon_selng_amt,thsmon_selng_co,mdwk_selng_amt,wkend_selng_amt,mon_selng_amt,tues_selng_amt,wed_selng_amt,thur_selng_amt,...,tmzon_17_21_selng_co,tmzon_21_24_selng_co,ml_selng_co,fml_selng_co,agrde_10_selng_co,agrde_20_selng_co,agrde_30_selng_co,agrde_40_selng_co,agrde_50_selng_co,agrde_60_above_selng_co
count,"147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00",...,"147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00","147,035.00"
mean,"20,252.50","3,110,554.79","874,412,675.29","34,535.26","667,788,231.40","206,624,443.89","132,304,760.66","130,710,571.62","130,899,549.74","128,412,652.06",...,"9,194.91","2,958.34","17,715.51","15,851.90",389.34,"4,719.47","7,044.20","6,233.31","6,977.53","8,203.59"
std,1.12,310.11,"3,359,618,665.43","109,309.59","2,607,618,058.11","850,467,176.00","530,979,440.04","533,725,145.14","535,025,600.65","513,018,350.48",...,"24,627.60","10,467.94","54,537.45","54,696.78","2,138.53","16,617.96","20,597.36","17,959.39","21,831.77","47,620.84"
min,"20,251.00","3,110,001.00",226.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,"20,251.00","3,110,281.00","52,495,868.00",776.00,"39,550,690.00","7,532,522.50","6,048,959.50","6,162,096.00","6,415,094.00","6,305,601.00",...,194.00,0.00,342.00,297.00,0.00,21.00,84.00,130.00,147.00,122.00
50%,"20,252.00","3,110,561.00","200,805,906.00","4,186.00","151,001,697.00","40,344,389.00","27,405,385.00","27,613,357.00","28,203,423.00","27,953,039.00",...,"1,135.00",38.00,"2,074.00","1,723.00",5.00,240.00,577.00,749.00,910.00,855.00
75%,"20,253.00","3,110,823.00","691,157,192.50","22,649.00","524,939,259.50","156,034,854.00","100,504,284.00","101,112,911.00","101,889,132.00","100,039,699.50",...,"6,167.50",879.00,"10,891.50","10,593.50",129.00,"2,135.00","3,889.50","3,972.00","4,632.50","4,710.00"
max,"20,254.00","3,111,090.00","280,618,285,025.00","12,136,730.00","197,454,147,851.00","84,853,558,483.00","36,513,375,847.00","40,227,070,715.00","43,001,594,432.00","46,114,868,534.00",...,"1,528,414.00","268,310.00","5,323,380.00","6,760,072.00","254,935.00","619,104.00","736,063.00","1,411,521.00","2,391,432.00","7,535,945.00"

In [21]:
import pandas as pd

# 숫자 하나를 한국식 단위로 바꾸는 함수
def 한국식(x, 소수=1):
    if pd.isna(x):
        return ''
    부호 = '-' if x < 0 else ''
    x = abs(x)
    for 기준, 단위 in [(1e12, '조'), (1e8, '억'), (1e4, '만')]:
        if x >= 기준:
            return f"{부호}{x/기준:,.{소수}f}{단위}"
    return f"{부호}{x:,.0f}" if x == int(x) else f"{부호}{x:,.2f}"

# describe() 결과에서 숫자만 한국식으로 바꾸기 (행·컬럼 이름은 그대로)
def 보기좋은_기초통계(df, 제외=None):
    num = df.select_dtypes('number')
    if 제외:
        num = num.drop(columns=[c for c in 제외 if c in num.columns])
    결과 = num.describe()
    if hasattr(결과, 'map'):          # pandas 2.1 이상
        return 결과.map(한국식)
    return 결과.applymap(한국식)       # pandas 2.1 미만

# 클래스 사용 및 출력
display(보기좋은_기초통계(store, 제외=['stdr_yyqu_cd', 'trdar_cd']))
display(보기좋은_기초통계(change, 제외=['기준_년분기_코드', '상권_코드']))
display(보기좋은_기초통계(sales, 제외=['기준_년분기_코드', '상권_코드']))
display(보기좋은_기초통계(sales_bg, 제외=['stdr_yyqu_cd', 'trdar_cd']))

,stor_co,similr_induty_stor_co,opbiz_rt,opbiz_stor_co,clsbiz_rt,clsbiz_stor_co,frc_stor_co
count,30.5만,30.5만,30.5만,30.5만,30.5만,30.5만,30.5만
mean,6.26,6.79,1.99,0.13,2.33,0.17,0.53
std,51.47,51.86,10.09,0.60,11.71,1.26,2.39
min,0,0,0,0,0,0,0
25%,1,1,0,0,0,0,0
50%,2,2,0,0,0,0,0
75%,5,5,0,0,0,0,0
max,1.1만,1.1만,200,28,450,291,151

      운영_영업_개월_평균 폐업_영업_개월_평균 서울_운영_영업_개월_평균 서울_폐업_영업_개월_평균
count        3.6만        3.6만           3.6만           3.6만
mean       109.67       52.66         103.95          51.36
std         26.00       10.70           7.40           1.43
min             3          20             94             49
25%            94          47             98             50
50%           106          51         101.50             51
75%           121          56            111             52
max           351         226            118             54

,당월_매출_금액,당월_매출_건수,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,...,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수
count,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,...,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만,8.6만
mean,10.8억,3.6만,8.2억,2.7억,1.6억,1.6억,1.6억,1.6억,1.8억,1.6억,...,"8,973.50","2,677.53",1.7만,1.6만,395.81,"5,330.24","7,935.12","6,611.03","6,549.41","7,158.44"
std,91.9억,17.3만,61.9억,33.3억,11.8억,12.0억,12.4억,12.3억,14.4억,19.4억,...,4.4만,1.1만,8.4만,8.6만,"2,431.12",2.7만,3.8만,3.2만,3.3만,5.9만
min,31,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25%,"4,583.8만",770,"3,377.6만",712.5만,512.1만,528.9만,561.6만,562.5만,616.3만,455.3만,...,192,0,345,301,0,24,89,134,148,112
50%,1.7억,"4,124",1.3억,"3,585.0만","2,266.6만","2,332.3만","2,397.7만","2,391.6만","2,640.8만","2,272.8만",...,"1,107.50",50,"2,015","1,749.50",7,285,649,751,852,723
75%,6.2억,2.2만,4.7억,1.4억,"8,872.1만","8,950.8만","9,116.6만","8,967.2만","9,993.1만","8,740.9만",...,"5,739.25",958.25,1.1만,"9,816.25",114,"2,189.25","4,038","3,884","4,286","3,927.25"
max,1.1조,"1,329.9만","7,029.8억","4,460.1억","1,122.1억","1,191.8억","1,445.5억","1,452.0억","1,818.4억","2,684.2억",...,439.9만,52.1만,723.2만,511.0만,18.0만,160.0만,259.3만,197.9만,238.1만,496.6만

,thsmon_selng_amt,thsmon_selng_co,mdwk_selng_amt,wkend_selng_amt,mon_selng_amt,tues_selng_amt,wed_selng_amt,thur_selng_amt,fri_selng_amt,sat_selng_amt,...,tmzon_17_21_selng_co,tmzon_21_24_selng_co,ml_selng_co,fml_selng_co,agrde_10_selng_co,agrde_20_selng_co,agrde_30_selng_co,agrde_40_selng_co,agrde_50_selng_co,agrde_60_above_selng_co
count,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,...,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만,14.7만
mean,8.7억,3.5만,6.7억,2.1억,1.3억,1.3억,1.3억,1.3억,1.5억,1.3억,...,"9,194.91","2,958.34",1.8만,1.6만,389.34,"4,719.47","7,044.20","6,233.31","6,977.53","8,203.59"
std,33.6억,10.9만,26.1억,8.5억,5.3억,5.3억,5.4억,5.1억,5.8억,5.1억,...,2.5만,1.0만,5.5만,5.5만,"2,138.53",1.7만,2.1만,1.8만,2.2만,4.8만
min,226,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25%,"5,249.6만",776,"3,955.1만",753.3만,604.9만,616.2만,641.5만,630.6만,677.7만,491.4만,...,194,0,342,297,0,21,84,130,147,122
50%,2.0억,"4,186",1.5억,"4,034.4만","2,740.5만","2,761.3만","2,820.3만","2,795.3만","3,078.4만","2,626.9만",...,"1,135",38,"2,074","1,723",5,240,577,749,910,855
75%,6.9억,2.3만,5.2억,1.6억,1.0억,1.0억,1.0억,1.0억,1.1억,1.0억,...,"6,167.50",879,1.1만,1.1만,129,"2,135","3,889.50","3,972","4,632.50","4,710"
max,"2,806.2억","1,213.7만","1,974.5억",848.5억,365.1억,402.3억,430.0억,461.1억,416.9억,521.1억,...,152.8만,26.8만,532.3만,676.0만,25.5만,61.9만,73.6만,141.2만,239.1만,753.6만

In [16]:
sales_cols = [
    '당월_매출_금액',
    '당월_매출_건수',
    '주중_매출_금액',
    '주말_매출_금액'
]

display(
    sales[sales_cols]
    .describe()
    .T
    .round(2)
)

,count,mean,std,min,25%,50%,75%,max
당월_매출_금액,85732.0,1.080789e+09,9.191795e+09,31.0,45838107.0,172136309.0,6.159625e+08,1.148994e+12
당월_매출_건수,85732.0,3.560820e+04,1.732327e+05,1.0,770.0,4124.0,2.157225e+04,1.329939e+07
주중_매출_금액,85732.0,8.156915e+08,6.192214e+09,0.0,33776424.0,127997622.5,4.669483e+08,7.029800e+11
주말_매출_금액,85732.0,2.650978e+08,3.329909e+09,0.0,7125408.5,35850116.5,1.375372e+08,4.460139e+11

In [17]:
# 숫자 출력 형식 설정
pd.set_option('display.float_format', '{:,.2f}'.format)

# 핵심 변수 기초통계
cols = [
    '당월_매출_금액',
    '당월_매출_건수',
    '주중_매출_금액',
    '주말_매출_금액'
]

display(sales[cols].describe().T.round(2))

,count,mean,std,min,25%,50%,75%,max
당월_매출_금액,"85,732.00","1,080,789,331.95","9,191,794,782.76",31.00,"45,838,107.00","172,136,309.00","615,962,477.25","1,148,993,825,259.00"
당월_매출_건수,"85,732.00","35,608.20","173,232.72",1.00,770.00,"4,124.00","21,572.25","13,299,388.00"
주중_매출_금액,"85,732.00","815,691,541.68","6,192,213,546.09",0.00,"33,776,424.00","127,997,622.50","466,948,320.25","702,979,967,421.00"
주말_매출_금액,"85,732.00","265,097,790.27","3,329,908,680.33",0.00,"7,125,408.50","35,850,116.50","137,537,196.00","446,013,857,838.00"