In [22]:
from IPython.display import display, HTML

display(HTML("""
<style>

/* =========================
전체 레이아웃
========================= */

div.container{
    width:85% !important;
}

div.cell.code_cell.rendered{
    width:100%;
}

div.input_prompt{
    padding:0;
}

div.prompt{
    min-width:70px;
}

div#toc-wrapper{
    padding-top:120px;
}

table.dataframe{
    font-size:12px;
}

/* =========================
   코드 입력창
========================= */

div.CodeMirror{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
    line-height:1.6;
}

/* =========================
   입력 셀
========================= */

div.input{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   코드 출력
========================= */

div.output{
    font-family:"마루 부리OTF 중간" !important;
    font-size:12pt !important;
}

/* =========================
   Markdown 전체
========================= */

.rendered_html{
    font-family:"마루 부리OTF 중간" !important;
    font-size:18px !important;
    line-height:1.8;
}

/* 제목 */

.rendered_html h1,
.rendered_html h2,
.rendered_html h3,
.rendered_html h4,
.rendered_html h5,
.rendered_html h6{
    font-family:"마루 부리OTF 조금굵은" !important;
}

/* 본문 */

.rendered_html p{
    font-family:"마루 부리OTF 중간" !important;
}

/* 리스트 */

.rendered_html li{
    font-family:"마루 부리OTF 중간" !important;
    padding:5px;
}

/* 인용 */

.rendered_html blockquote{
    font-family:"마루 부리OTF 중간" !important;
}

/* 표 */

.rendered_html table{
    font-family:"마루 부리OTF 중간" !important;
}

/* 코드 블록 */

.rendered_html pre,
.rendered_html code{
    font-family:"Consolas" !important;
    font-size:12pt !important;
}

</style>
"""))

In [23]:
import pandas as pd

In [24]:
# 데이터 수집 및 확인
store = pd.read_csv("./data/독립변수1_서울시 상권분석서비스(점포-상권)_2025년.csv", encoding="cp949")
change = pd.read_csv("./data/독립변수2_서울시 상권분석서비스(상권변화지표-상권).csv", encoding="cp949")
sales = pd.read_csv("./data/독립변수3_서울시 상권분석서비스(추정매출-상권)_2025년.csv", encoding="cp949")
sales_bg = pd.read_csv("./data/독립변수3_선택_서울시 상권분석서비스(추정매출-상권배후지)_2025년.csv", encoding="cp949")

# 데이터 크기 확인
print("점포-상권 :", store.shape)
print("상권변화지표-상권 :", change.shape)
print("추정매출-상권 :", sales.shape)
print("추정매출-상권배후지 :", sales_bg.shape)

점포-상권 : (304775, 14)
상권변화지표-상권 : (36300, 11)
추정매출-상권 : (85732, 55)
추정매출-상권배후지 : (147035, 55)

# 원본 보존
- 전처리하다 잘못 수정될 경우를 대비하여 원본을 먼저 복사.

In [25]:
# 원본 보존
store_clean = store.copy()
change_clean = change.copy()
sales_clean = sales.copy()
sales_bg_clean = sales_bg.copy()

In [26]:
# 중복 확인 및 처리
print("점포 데이터 중복 :", store_clean.duplicated().sum())
print("상권변화지표 중복 :", change_clean.duplicated().sum())
print("추정매출 중복 :", sales_clean.duplicated().sum())
print("상권배후지 중복 :", sales_bg_clean.duplicated().sum())

store_clean = store_clean.drop_duplicates()
change_clean = change_clean.drop_duplicates()
sales_clean = sales_clean.drop_duplicates()
sales_bg_clean = sales_bg_clean.drop_duplicates()

점포 데이터 중복 : 0
상권변화지표 중복 : 0
추정매출 중복 : 0
상권배후지 중복 : 0

# 컬럼명 표준화

In [28]:
# store 컬럼명 수정
store_clean = store_clean.rename(columns={
    'stdr_yyqu_cd': '기준년분기코드',
    'trdar_se_cd': '상권구분코드',
    'trdar_se_cd_nm': '상권구분코드명',
    'trdar_cd': '상권코드',
    'trdar_cd_nm': '상권코드명',
    'svc_induty_cd': '서비스업종코드',
    'svc_induty_cd_nm': '서비스업종코드명',
    'stor_co': '점포수',
    'similr_induty_stor_co': '유사업종점포수',
    'opbiz_rt': '개업률',
    'opbiz_stor_co': '개업점포수',
    'clsbiz_rt': '폐업률',
    'clsbiz_stor_co': '폐업점포수',
    'frc_stor_co': '프랜차이즈점포수'
})

In [29]:
change_clean.columns = change_clean.columns.str.replace('_', '', regex=False)
sales_clean.columns = sales_clean.columns.str.replace('_', '', regex=False)

In [30]:
sales_bg_clean = sales_bg_clean.rename(columns={
    # 기본 정보
    'stdr_yyqu_cd': '기준년분기코드',
    'trdar_se_cd': '상권구분코드',
    'trdar_se_cd_nm': '상권구분코드명',
    'trdar_cd': '상권코드',
    'trdar_cd_nm': '상권코드명',
    'svc_induty_cd': '서비스업종코드',
    'svc_induty_cd_nm': '서비스업종코드명',

    # 전체 매출
    'thsmon_selng_amt': '당월매출금액',
    'thsmon_selng_co': '당월매출건수',

    # 주중 / 주말 매출금액
    'mdwk_selng_amt': '주중매출금액',
    'wkend_selng_amt': '주말매출금액',

    # 요일별 매출금액
    'mon_selng_amt': '월요일매출금액',
    'tues_selng_amt': '화요일매출금액',
    'wed_selng_amt': '수요일매출금액',
    'thur_selng_amt': '목요일매출금액',
    'fri_selng_amt': '금요일매출금액',
    'sat_selng_amt': '토요일매출금액',
    'sun_selng_amt': '일요일매출금액',

    # 시간대별 매출금액
    'tmzon_00_06_selng_amt': '시간대00~06매출금액',
    'tmzon_06_11_selng_amt': '시간대06~11매출금액',
    'tmzon_11_14_selng_amt': '시간대11~14매출금액',
    'tmzon_14_17_selng_amt': '시간대14~17매출금액',
    'tmzon_17_21_selng_amt': '시간대17~21매출금액',
    'tmzon_21_24_selng_amt': '시간대21~24매출금액',

    # 성별 매출금액
    'ml_selng_amt': '남성매출금액',
    'fml_selng_amt': '여성매출금액',

    # 연령대별 매출금액
    'agrde_10_selng_amt': '연령대10매출금액',
    'agrde_20_selng_amt': '연령대20매출금액',
    'agrde_30_selng_amt': '연령대30매출금액',
    'agrde_40_selng_amt': '연령대40매출금액',
    'agrde_50_selng_amt': '연령대50매출금액',
    'agrde_60_above_selng_amt': '연령대60이상매출금액',

    # 주중 / 주말 매출건수
    'mdwk_selng_co': '주중매출건수',
    'wkend_selng_co': '주말매출건수',

    # 요일별 매출건수
    'mon_selng_co': '월요일매출건수',
    'tues_selng_co': '화요일매출건수',
    'wed_selng_co': '수요일매출건수',
    'thur_selng_co': '목요일매출건수',
    'fri_selng_co': '금요일매출건수',
    'sat_selng_co': '토요일매출건수',
    'sun_selng_co': '일요일매출건수',

    # 시간대별 매출건수
    'tmzon_00_06_selng_co': '시간대00~06매출건수',
    'tmzon_06_11_selng_co': '시간대06~11매출건수',
    'tmzon_11_14_selng_co': '시간대11~14매출건수',
    'tmzon_14_17_selng_co': '시간대14~17매출건수',
    'tmzon_17_21_selng_co': '시간대17~21매출건수',
    'tmzon_21_24_selng_co': '시간대21~24매출건수',

    # 성별 매출건수
    'ml_selng_co': '남성매출건수',
    'fml_selng_co': '여성매출건수',

    # 연령대별 매출건수
    'agrde_10_selng_co': '연령대10매출건수',
    'agrde_20_selng_co': '연령대20매출건수',
    'agrde_30_selng_co': '연령대30매출건수',
    'agrde_40_selng_co': '연령대40매출건수',
    'agrde_50_selng_co': '연령대50매출건수',
    'agrde_60_above_selng_co': '연령대60이상매출건수'
})

In [31]:
print("=== 점포-상권 ===")
print(store_clean.columns.tolist())

print("\n=== 상권변화지표-상권 ===")
print(change_clean.columns.tolist())

print("\n=== 추정매출-상권 ===")
print(sales_clean.columns.tolist())

print("\n=== 추정매출-상권배후지 ===")
print(sales_bg_clean.columns.tolist())

=== 점포-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '점포수', '유사업종점포수', '개업률', '개업점포수', '폐업률', '폐업점포수', '프랜차이즈점포수']

=== 상권변화지표-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '상권변화지표', '상권변화지표명', '운영영업개월평균', '폐업영업개월평균', '서울운영영업개월평균', '서울폐업영업개월평균']

=== 추정매출-상권 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대00~06매출금액', '시간대06~11매출금액', '시간대11~14매출금액', '시간대14~17매출금액', '시간대17~21매출금액', '시간대21~24매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대건수~06매출건수', '시간대건수~11매출건수', '시간대건수~14매출건수', '시간대건수~17매출건수', '시간대건수~21매출건수', '시간대건수~24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']

=== 추정매출-상권배후지 ===
['기준년분기코드', '상권구분코드', '상권구분코드명', '상권코드', '상권코드명', '서비스업종코드', '서비스업종코드명', '당월매출금액', '당월매출건수', '주중매출금액', '주말매출금액', '월요일매출금액', '화요일매출금액', '수요일매출금액', '목요일매출금액', '금요일매출금액', '토요일매출금액', '일요일매출금액', '시간대00~06매출금액', '시간대06~11매출금액', '시간대11~14매출금액', '시간대14~17매출금액', '시간대17~21매출금액', '시간대21~24매출금액', '남성매출금액', '여성매출금액', '연령대10매출금액', '연령대20매출금액', '연령대30매출금액', '연령대40매출금액', '연령대50매출금액', '연령대60이상매출금액', '주중매출건수', '주말매출건수', '월요일매출건수', '화요일매출건수', '수요일매출건수', '목요일매출건수', '금요일매출건수', '토요일매출건수', '일요일매출건수', '시간대00~06매출건수', '시간대06~11매출건수', '시간대11~14매출건수', '시간대14~17매출건수', '시간대17~21매출건수', '시간대21~24매출건수', '남성매출건수', '여성매출건수', '연령대10매출건수', '연령대20매출건수', '연령대30매출건수', '연령대40매출건수', '연령대50매출건수', '연령대60이상매출건수']

# 자료형 확인 및 통일

In [37]:
# 병합에 사용할 주요 컬럼 자료형 확인
# 병합에 사용할 주요 컬럼 자료형 확인

print("=== 점포-상권 ===")
print(store_clean[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 상권변화지표-상권 ===")
print(change_clean[
    ['기준년분기코드', '상권코드']
].dtypes)

print("\n=== 추정매출-상권 ===")
print(sales_clean[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

print("\n=== 추정매출-상권배후지 ===")
print(sales_bg_clean[
    ['기준년분기코드', '상권코드', '서비스업종코드']
].dtypes)

=== 점포-상권 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 상권변화지표-상권 ===
기준년분기코드    int64
상권코드       int64
dtype: object

=== 추정매출-상권 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

=== 추정매출-상권배후지 ===
기준년분기코드     int64
상권코드        int64
서비스업종코드    object
dtype: object

In [38]:
# change는 서비스업종 컬럼 자체가 없으므로 -> 기준년분기코드, 상권코드만 결합하는 구조로 확인
print(store_clean[['기준년분기코드','상권코드']].dtypes)
print(change_clean[['기준년분기코드','상권코드']].dtypes)
print(sales_clean[['기준년분기코드','상권코드']].dtypes)
print(sales_bg_clean[['기준년분기코드','상권코드']].dtypes)

기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object
기준년분기코드    int64
상권코드       int64
dtype: object

# 중복값 확인 및 처리

In [39]:
# 중복값 확인
print("점포-상권:", store_clean.duplicated().sum())
print("상권변화지표-상권:", change_clean.duplicated().sum())
print("추정매출-상권:", sales_clean.duplicated().sum())
print("추정매출-상권배후지:", sales_bg_clean.duplicated().sum())

점포-상권: 0
상권변화지표-상권: 0
추정매출-상권: 0
추정매출-상권배후지: 0

In [40]:
# 중복이 존재할 때만
# store_clean = store_clean.drop_duplicates()
# change_clean = change_cleann.drop_duplicates()
# sales_clean = sales_clean.drop_duplicates()
# sales_bg_clean = sales_bg_clean.drop_duplicates()

# 결측치 확인 및 처리

In [41]:
# 결측치 확인 및 처리
def missing_check(df):
    result = pd.DataFrame({
        "결측치": df.isnull().sum(),
        "결측률(%)": (df.isnull().mean() * 100).round(2)
    })

    return result[result["결측치"] > 0]

display(missing_check(store_clean))
display(missing_check(change_clean))
display(missing_check(sales_clean))
display(missing_check(sales_bg_clean))

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

Empty DataFrame
Columns: [결측치, 결측률(%)]
Index: []

# 이상치 확인 및 검토

In [45]:
# 기초통계 확인
print("===== 점포-상권 =====")
display(store_clean.describe().T)

print("===== 상권변화지표-상권 =====")
display(change_clean.describe().T)

print("===== 추정매출-상권 =====")
display(sales_clean.describe().T)

print("===== 추정매출-상권배후지 =====")
display(sales_bg_clean.describe().T)

===== 점포-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,304775.0,2.025250e+04,1.117977,20251.0,20251.0,20252.0,20253.0,20254.0
상권코드,304775.0,3.114805e+06,11759.368732,3001491.0,3110437.0,3110871.0,3120138.0,3130327.0
점포수,304775.0,6.257065e+00,51.466804,0.0,1.0,2.0,5.0,11433.0
유사업종점포수,304775.0,6.790308e+00,51.863075,0.0,1.0,2.0,5.0,11444.0
개업률,304775.0,1.987030e+00,10.086123,0.0,0.0,0.0,0.0,200.0
개업점포수,304775.0,1.300730e-01,0.601829,0.0,0.0,0.0,0.0,28.0
폐업률,304775.0,2.334539e+00,11.706172,0.0,0.0,0.0,0.0,450.0
폐업점포수,304775.0,1.719268e-01,1.263042,0.0,0.0,0.0,0.0,291.0
프랜차이즈점포수,304775.0,5.332426e-01,2.389032,0.0,0.0,0.0,0.0,151.0

===== 상권변화지표-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,36300.0,2.023514e+04,15.889882,20211.0,20222.0,20233.5,20251.0,20262.0
상권코드,36300.0,3.115222e+06,10318.672722,3001491.0,3110407.0,3110819.5,3120142.0,3130327.0
운영영업개월평균,36300.0,1.096680e+02,26.002545,3.0,94.0,106.0,121.0,351.0
폐업영업개월평균,36300.0,5.265565e+01,10.704805,20.0,47.0,51.0,56.0,226.0
서울운영영업개월평균,36300.0,1.039545e+02,7.400822,94.0,98.0,101.5,111.0,118.0
서울폐업영업개월평균,36300.0,5.136364e+01,1.431658,49.0,50.0,51.0,52.0,54.0

===== 추정매출-상권 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,85732.0,2.025250e+04,1.116933e+00,20251.0,20252.00,20252.0,2.025300e+04,2.025400e+04
상권코드,85732.0,3.115456e+06,1.415781e+04,3001491.0,3110534.00,3111072.5,3.120183e+06,3.130327e+06
당월매출금액,85732.0,1.080789e+09,9.191795e+09,31.0,45838107.00,172136309.0,6.159625e+08,1.148994e+12
당월매출건수,85732.0,3.560820e+04,1.732327e+05,1.0,770.00,4124.0,2.157225e+04,1.329939e+07
주중매출금액,85732.0,8.156915e+08,6.192214e+09,0.0,33776424.00,127997622.5,4.669483e+08,7.029800e+11
주말매출금액,85732.0,2.650978e+08,3.329909e+09,0.0,7125408.50,35850116.5,1.375372e+08,4.460139e+11
월요일매출금액,85732.0,1.585188e+08,1.180792e+09,0.0,5121054.75,22665597.5,8.872094e+07,1.122125e+11
화요일매출금액,85732.0,1.597231e+08,1.196965e+09,0.0,5289032.00,23322686.0,8.950829e+07,1.191794e+11
수요일매출금액,85732.0,1.599394e+08,1.236434e+09,0.0,5616288.25,23977429.5,9.116630e+07,1.445473e+11
목요일매출금액,85732.0,1.587210e+08,1.225512e+09,0.0,5624929.25,23916224.0,8.967224e+07,1.452027e+11
금요일매출금액,85732.0,1.787891e+08,1.435676e+09,0.0,6163400.75,26408262.0,9.993116e+07,1.818381e+11
토요일매출금액,85732.0,1.643153e+08,1.935650e+09,0.0,4552780.75,22728233.0,8.740899e+07,2.684213e+11
일요일매출금액,85732.0,1.007825e+08,1.428440e+09,0.0,0.00,8722062.0,4.583815e+07,1.775926e+11
시간대00~06매출금액,85732.0,3.799190e+07,8.607884e+08,0.0,0.00,0.0,3.254136e+06,1.266549e+11
시간대06~11매출금액,85732.0,1.293082e+08,1.446269e+09,0.0,219775.50,6667712.0,4.659506e+07,1.643040e+11
시간대11~14매출금액,85732.0,2.825852e+08,2.257160e+09,0.0,5528060.25,33477431.0,1.441812e+08,2.271113e+11
시간대14~17매출금액,85732.0,2.655601e+08,2.744876e+09,0.0,7401949.50,32608535.0,1.272428e+08,2.759481e+11
시간대17~21매출금액,85732.0,2.829528e+08,2.705338e+09,0.0,10504726.50,44658789.5,1.656352e+08,4.102962e+11
시간대21~24매출금액,85732.0,8.239107e+07,5.168120e+08,0.0,0.00,2712248.0,3.452531e+07,4.199821e+10
남성매출금액,85732.0,4.899551e+08,4.396794e+09,0.0,18280310.25,76770266.5,2.863432e+08,5.936228e+11
여성매출금액,85732.0,4.681600e+08,3.728371e+09,0.0,16907146.00,69141832.5,2.598762e+08,3.687561e+11
연령대10매출금액,85732.0,4.275442e+06,2.610628e+07,0.0,0.00,73672.0,1.554914e+06,1.385634e+09
연령대20매출금액,85732.0,9.672955e+07,7.249668e+08,0.0,738891.00,8342505.5,4.402626e+07,1.018944e+11
연령대30매출금액,85732.0,1.878695e+08,1.617797e+09,0.0,3982116.00,23108759.5,9.813289e+07,2.055992e+11
연령대40매출금액,85732.0,2.122886e+08,1.723246e+09,0.0,6371059.25,30461045.5,1.165229e+08,1.638682e+11
연령대50매출금액,85732.0,2.149905e+08,1.904994e+09,0.0,7871619.75,33543904.5,1.240934e+08,1.918168e+11
연령대60이상매출금액,85732.0,2.419627e+08,2.510243e+09,0.0,5389267.25,26276566.5,1.119474e+08,2.980817e+11
주중매출건수,85732.0,2.663086e+04,1.175179e+05,0.0,585.00,3046.0,1.618925e+04,7.468026e+06
주말매출건수,85732.0,8.977341e+03,6.078342e+04,0.0,132.00,933.0,5.090500e+03,5.831362e+06
월요일매출건수,85732.0,5.249032e+03,2.252447e+04,0.0,102.00,567.0,3.165000e+03,1.140818e+06
화요일매출건수,85732.0,5.176356e+03,2.265854e+04,0.0,103.00,576.0,3.136000e+03,1.191447e+06
수요일매출건수,85732.0,5.261076e+03,2.317981e+04,0.0,109.00,602.0,3.201000e+03,1.637572e+06
목요일매출건수,85732.0,5.282964e+03,2.356315e+04,0.0,109.00,599.0,3.192250e+03,1.510741e+06
금요일매출건수,85732.0,5.661433e+03,2.610529e+04,0.0,119.00,670.0,3.456000e+03,2.036222e+06
토요일매출건수,85732.0,5.223276e+03,3.427878e+04,0.0,91.00,603.0,3.084000e+03,3.442309e+06
일요일매출건수,85732.0,3.754066e+03,2.686122e+04,0.0,0.00,233.0,1.845000e+03,2.389053e+06
시간대건수~06매출건수,85732.0,1.159285e+03,1.015782e+04,0.0,0.00,0.0,8.100000e+01,1.148437e+06
시간대건수~11매출건수,85732.0,5.249373e+03,3.064082e+04,0.0,8.00,171.0,1.811000e+03,1.676457e+06
시간대건수~14매출건수,85732.0,9.743859e+03,5.015622e+04,0.0,104.00,920.0,5.723000e+03,3.065320e+06
시간대건수~17매출건수,85732.0,7.804662e+03,5.158059e+04,0.0,155.00,880.0,4.417000e+03,4.054339e+06
시간대건수~21매출건수,85732.0,8.973499e+03,4.442740e+04,0.0,192.00,1107.5,5.739250e+03,4.399314e+06
시간대건수~24매출건수,85732.0,2.677525e+03,1.141530e+04,0.0,0.00,50.0,9.582500e+02,5.208220e+05
남성매출건수,85732.0,1.748732e+04,8.368368e+04,0.0,345.00,2015.0,1.050700e+04,7.231893e+06
여성매출건수,85732.0,1.649272e+04,8.606268e+04,0.0,301.00,1749.5,9.816250e+03,5.110243e+06
연령대10매출건수,85732.0,3.958139e+02,2.431120e+03,0.0,0.00,7.0,1.140000e+02,1.796800e+05
연령대20매출건수,85732.0,5.330241e+03,2.732389e+04,0.0,24.00,285.0,2.189250e+03,1.599813e+06
연령대30매출건수,85732.0,7.935116e+03,3.816054e+04,0.0,89.00,649.0,4.038000e+03,2.592933e+06
연령대40매출건수,85732.0,6.611026e+03,3.159775e+04,0.0,134.00,751.0,3.884000e+03,1.979297e+06
연령대50매출건수,85732.0,6.549409e+03,3.340550e+04,0.0,148.00,852.0,4.286000e+03,2.381030e+06
연령대60이상매출건수,85732.0,7.158441e+03,5.913484e+04,0.0,112.00,723.0,3.927250e+03,4.965867e+06

===== 추정매출-상권배후지 =====

,count,mean,std,min,25%,50%,75%,max
기준년분기코드,147035.0,2.025250e+04,1.117314e+00,20251.0,20251.0,20252.0,20253.0,2.025400e+04
상권코드,147035.0,3.110555e+06,3.101068e+02,3110001.0,3110281.0,3110561.0,3110823.0,3.111090e+06
당월매출금액,147035.0,8.744127e+08,3.359619e+09,226.0,52495868.0,200805906.0,691157192.5,2.806183e+11
당월매출건수,147035.0,3.453526e+04,1.093096e+05,1.0,776.0,4186.0,22649.0,1.213673e+07
주중매출금액,147035.0,6.677882e+08,2.607618e+09,0.0,39550690.0,151001697.0,524939259.5,1.974541e+11
주말매출금액,147035.0,2.066244e+08,8.504672e+08,0.0,7532522.5,40344389.0,156034854.0,8.485356e+10
월요일매출금액,147035.0,1.323048e+08,5.309794e+08,0.0,6048959.5,27405385.0,100504284.0,3.651338e+10
화요일매출금액,147035.0,1.307106e+08,5.337251e+08,0.0,6162096.0,27613357.0,101112911.0,4.022707e+10
수요일매출금액,147035.0,1.308995e+08,5.350256e+08,0.0,6415094.0,28203423.0,101889132.0,4.300159e+10
목요일매출금액,147035.0,1.284127e+08,5.130184e+08,0.0,6305601.0,27953039.0,100039699.5,4.611487e+10
금요일매출금액,147035.0,1.454607e+08,5.804185e+08,0.0,6776737.0,30783789.0,111623679.0,4.168915e+10
토요일매출금액,147035.0,1.294033e+08,5.148848e+08,0.0,4914427.0,26268658.0,100460835.5,5.211350e+10
일요일매출금액,147035.0,7.722112e+07,3.495472e+08,0.0,0.0,8705094.0,49284741.0,3.522756e+10
시간대00~06매출금액,147035.0,2.780004e+07,1.668070e+08,0.0,0.0,0.0,2587859.0,1.776404e+10
시간대06~11매출금액,147035.0,1.111500e+08,7.730638e+08,0.0,529625.0,9590308.0,63478853.0,7.603059e+10
시간대11~14매출금액,147035.0,2.217910e+08,1.036216e+09,0.0,6195728.5,38302391.0,159954919.5,9.805352e+10
시간대14~17매출금액,147035.0,2.092665e+08,1.033764e+09,0.0,9194585.0,40698843.0,160619696.5,9.775088e+10
시간대17~21매출금액,147035.0,2.332306e+08,7.172946e+08,0.0,11856288.0,52665054.0,178534995.0,4.986249e+10
시간대21~24매출금액,147035.0,7.117452e+07,2.804160e+08,0.0,0.0,2313762.0,29791174.0,1.563545e+10
남성매출금액,147035.0,4.183382e+08,1.604538e+09,0.0,20830566.5,89412141.0,320965264.0,1.201562e+11
여성매출금액,147035.0,3.851588e+08,1.587873e+09,0.0,18282198.0,80394709.0,302507763.0,1.520222e+11
연령대10매출금액,147035.0,3.380291e+06,1.441472e+07,0.0,0.0,44818.0,1812381.5,9.548834e+08
연령대20매출금액,147035.0,7.139787e+07,2.580528e+08,0.0,658389.5,8538121.0,44932490.5,1.231870e+10
연령대30매출금액,147035.0,1.400221e+08,4.536471e+08,0.0,4035505.0,24996405.0,103004359.0,2.305195e+10
연령대40매출금액,147035.0,1.698790e+08,7.211319e+08,0.0,6666462.5,34965147.0,130800512.5,7.914422e+10
연령대50매출금액,147035.0,1.893766e+08,7.982953e+08,0.0,8954890.5,40488899.0,148181823.0,6.001640e+10
연령대60이상매출금액,147035.0,2.294426e+08,1.438531e+09,0.0,6835371.0,34154558.0,139870890.0,1.707403e+11
주중매출건수,147035.0,2.575129e+04,7.736855e+04,0.0,600.0,3127.0,16843.5,7.995098e+06
주말매출건수,147035.0,8.783976e+03,3.360298e+04,0.0,126.0,932.0,5578.0,4.161697e+06
월요일매출건수,147035.0,5.192373e+03,1.549471e+04,0.0,109.0,597.0,3253.5,1.483634e+06
화요일매출건수,147035.0,5.012569e+03,1.511654e+04,0.0,108.0,593.0,3278.0,1.613297e+06
수요일매출건수,147035.0,5.050041e+03,1.508731e+04,0.0,112.0,618.0,3336.0,1.748017e+06
목요일매출건수,147035.0,5.055084e+03,1.546761e+04,0.0,111.0,609.0,3326.0,1.686082e+06
금요일매출건수,147035.0,5.441221e+03,1.653056e+04,0.0,118.0,674.0,3635.0,1.798095e+06
토요일매출건수,147035.0,5.138569e+03,1.912948e+04,0.0,88.0,624.0,3450.0,2.442777e+06
일요일매출건수,147035.0,3.645407e+03,1.476412e+04,0.0,0.0,209.0,1891.0,1.877200e+06
시간대00~06매출건수,147035.0,1.255081e+03,6.059749e+03,0.0,0.0,0.0,71.0,2.761370e+05
시간대06~11매출건수,147035.0,5.050925e+03,2.022384e+04,0.0,14.0,211.0,2151.0,2.227916e+06
시간대11~14매출건수,147035.0,8.542400e+03,3.214716e+04,0.0,110.0,843.0,5801.0,4.300879e+06
시간대14~17매출건수,147035.0,7.533612e+03,3.197781e+04,0.0,178.0,941.0,5131.0,4.770585e+06
시간대17~21매출건수,147035.0,9.194906e+03,2.462760e+04,0.0,194.0,1135.0,6167.5,1.528414e+06
시간대21~24매출건수,147035.0,2.958340e+03,1.046794e+04,0.0,0.0,38.0,879.0,2.683100e+05
남성매출건수,147035.0,1.771551e+04,5.453745e+04,0.0,342.0,2074.0,10891.5,5.323380e+06
여성매출건수,147035.0,1.585190e+04,5.469678e+04,0.0,297.0,1723.0,10593.5,6.760072e+06
연령대10매출건수,147035.0,3.893358e+02,2.138530e+03,0.0,0.0,5.0,129.0,2.549350e+05
연령대20매출건수,147035.0,4.719473e+03,1.661796e+04,0.0,21.0,240.0,2135.0,6.191040e+05
연령대30매출건수,147035.0,7.044197e+03,2.059736e+04,0.0,84.0,577.0,3889.5,7.360630e+05
연령대40매출건수,147035.0,6.233305e+03,1.795939e+04,0.0,130.0,749.0,3972.0,1.411521e+06
연령대50매출건수,147035.0,6.977529e+03,2.183177e+04,0.0,147.0,910.0,4632.5,2.391432e+06
연령대60이상매출건수,147035.0,8.203590e+03,4.762084e+04,0.0,122.0,855.0,4710.0,7.535945e+06

In [48]:
# 식별자를 제외하도록 함수 수정
def check_outlier(df):
    # 수치형 컬럼 선택
    numeric_cols = df.select_dtypes(include='number').columns

    # 이상치 분석에서 제외할 식별자
    exclude_cols = [
        '기준년분기코드',
        '상권코드'
    ]

    numeric_cols = [
        col for col in numeric_cols
        if col not in exclude_cols
    ]

    result = []

    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outlier_count = (
            (df[col] < lower) |
            (df[col] > upper)
        ).sum()

        result.append([
            col,
            outlier_count,
            lower,
            upper
        ])

    return pd.DataFrame(
        result,
        columns=['컬럼명', '이상치후보수', '하한값', '상한값']
    )

In [54]:
print("=== 점포-상권 ===")
display(check_outlier(store_clean))
print("\n=== 상권변화지표-상권 ===")
display(check_outlier(change_clean))
print("\n=== 추정매출-상권 ===")
display(check_outlier(sales_clean))
print("\n=== 추정매출-상권배후지 ===")
display(check_outlier(sales_bg_clean))

=== 점포-상권 ===

        컬럼명  이상치후보수  하한값   상한값
0       점포수   29493 -5.0  11.0
1   유사업종점포수   32765 -5.0  11.0
2       개업률   26581  0.0   0.0
3     개업점포수   26716  0.0   0.0
4       폐업률   30246  0.0   0.0
5     폐업점포수   32379  0.0   0.0
6  프랜차이즈점포수   54489  0.0   0.0

=== 상권변화지표-상권 ===

          컬럼명  이상치후보수   하한값    상한값
0    운영영업개월평균    1588  53.5  161.5
1    폐업영업개월평균    1990  33.5   69.5
2  서울운영영업개월평균       0  78.5  130.5
3  서울폐업영업개월평균       0  47.0   55.0

=== 추정매출-상권 ===

             컬럼명  이상치후보수           하한값           상한값
0         당월매출금액   10779 -8.093484e+08  1.471149e+09
1         당월매출건수   12197 -3.043338e+04  5.277562e+04
2         주중매출금액   10725 -6.159814e+08  1.116706e+09
3         주말매출금액   10830 -1.884923e+08  3.331549e+08
4        월요일매출금액   10880 -1.202788e+08  2.141208e+08
5        화요일매출금액   10723 -1.210399e+08  2.158372e+08
6        수요일매출금액   10697 -1.227087e+08  2.194913e+08
7        목요일매출금액   10764 -1.204460e+08  2.157432e+08
8        금요일매출금액   10771 -1.344882e+08  2.405828e+08
9        토요일매출금액   10771 -1.197315e+08  2.116933e+08
10       일요일매출금액   11167 -6.875722e+07  1.145954e+08
11  시간대00~06매출금액   17515 -4.881204e+06  8.135340e+06
12  시간대06~11매출금액   12275 -6.934315e+07  1.161580e+08
13  시간대11~14매출금액   11228 -2.024517e+08  3.521610e+08
14  시간대14~17매출금액   11218 -1.723593e+08  3.070040e+08
15  시간대17~21매출금액   10799 -2.221910e+08  3.983310e+08
16  시간대21~24매출금액   12545 -5.178796e+07  8.631327e+07
17        남성매출금액   10728 -3.838140e+08  6.884374e+08
18        여성매출금액   10860 -3.475465e+08  6.243299e+08
19     연령대10매출금액   13076 -2.332371e+06  3.887286e+06
20     연령대20매출금액   11606 -6.419216e+07  1.089573e+08
21     연령대30매출금액   10924 -1.372440e+08  2.393590e+08
22     연령대40매출금액   10639 -1.588566e+08  2.817505e+08
23     연령대50매출금액   10696 -1.664611e+08  2.984261e+08
24   연령대60이상매출금액   11776 -1.544479e+08  2.717845e+08
25        주중매출건수   12188 -2.282138e+04  3.959562e+04
26        주말매출건수   12308 -7.305750e+03  1.252825e+04
27       월요일매출건수   12218 -4.492500e+03  7.759500e+03
28       화요일매출건수   12094 -4.446500e+03  7.685500e+03
29       수요일매출건수   12099 -4.529000e+03  7.839000e+03
30       목요일매출건수   12193 -4.515875e+03  7.817125e+03
31       금요일매출건수   12080 -4.886500e+03  8.461500e+03
32       토요일매출건수   12136 -4.398500e+03  7.573500e+03
33       일요일매출건수   12896 -2.767500e+03  4.612500e+03
34  시간대건수~06매출건수   17316 -1.215000e+02  2.025000e+02
35  시간대건수~11매출건수   14442 -2.696500e+03  4.515500e+03
36  시간대건수~14매출건수   11631 -8.324500e+03  1.415150e+04
37  시간대건수~17매출건수   12150 -6.238000e+03  1.081000e+04
38  시간대건수~21매출건수   12149 -8.128875e+03  1.406012e+04
39  시간대건수~24매출건수   14456 -1.437375e+03  2.395625e+03
40        남성매출건수   12281 -1.489800e+04  2.575000e+04
41        여성매출건수   12094 -1.397188e+04  2.408912e+04
42     연령대10매출건수   14004 -1.710000e+02  2.850000e+02
43     연령대20매출건수   13242 -3.223875e+03  5.437125e+03
44     연령대30매출건수   12475 -5.834500e+03  9.961500e+03
45     연령대40매출건수   12310 -5.491000e+03  9.509000e+03
46     연령대50매출건수   12095 -6.059000e+03  1.049300e+04
47   연령대60이상매출건수   12265 -5.610875e+03  9.650125e+03

=== 추정매출-상권배후지 ===

             컬럼명  이상치후보수           하한값           상한값
0         당월매출금액   18319 -9.054961e+08  1.649149e+09
1         당월매출건수   22719 -3.203350e+04  5.545850e+04
2         주중매출금액   18452 -6.885322e+08  1.253022e+09
3         주말매출금액   17873 -2.152210e+08  3.787884e+08
4        월요일매출금액   18883 -1.356340e+08  2.421873e+08
5        화요일매출금액   18527 -1.362641e+08  2.435391e+08
6        수요일매출금액   18412 -1.367960e+08  2.451002e+08
7        목요일매출금액   18336 -1.342955e+08  2.406408e+08
8        금요일매출금액   18582 -1.504937e+08  2.688941e+08
9        토요일매출금액   17925 -1.384052e+08  2.437804e+08
10       일요일매출금액   18778 -7.392711e+07  1.232119e+08
11  시간대00~06매출금액   30554 -3.881788e+06  6.469648e+06
12  시간대06~11매출금액   20652 -9.389422e+07  1.579027e+08
13  시간대11~14매출금액   18365 -2.244431e+08  3.905937e+08
14  시간대14~17매출금액   18333 -2.179431e+08  3.877574e+08
15  시간대17~21매출금액   17565 -2.381618e+08  4.285531e+08
16  시간대21~24매출금액   22975 -4.468676e+07  7.447794e+07
17        남성매출금액   18756 -4.293715e+08  7.711673e+08
18        여성매출금액   18517 -4.080561e+08  7.288461e+08
19     연령대10매출금액   22075 -2.718572e+06  4.530954e+06
20     연령대20매출금액   20145 -6.575276e+07  1.113436e+08
21     연령대30매출금액   18767 -1.444178e+08  2.514576e+08
22     연령대40매출금액   18315 -1.795346e+08  3.170016e+08
23     연령대50매출금액   18253 -1.998855e+08  3.570222e+08
24   연령대60이상매출금액   20752 -1.927179e+08  3.394242e+08
25        주중매출건수   22695 -2.376525e+04  4.120875e+04
26        주말매출건수   22383 -8.052000e+03  1.375600e+04
27       월요일매출건수   23114 -4.607750e+03  7.970250e+03
28       화요일매출건수   22639 -4.647000e+03  8.033000e+03
29       수요일매출건수   22591 -4.724000e+03  8.172000e+03
30       목요일매출건수   22676 -4.711500e+03  8.148500e+03
31       금요일매출건수   22424 -5.157500e+03  8.910500e+03
32       토요일매출건수   22125 -4.955000e+03  8.493000e+03
33       일요일매출건수   23192 -2.836500e+03  4.727500e+03
34  시간대00~06매출건수   30660 -1.065000e+02  1.775000e+02
35  시간대06~11매출건수   24956 -3.191500e+03  5.356500e+03
36  시간대11~14매출건수   21943 -8.426500e+03  1.433750e+04
37  시간대14~17매출건수   22167 -7.251500e+03  1.256050e+04
38  시간대17~21매출건수   21815 -8.766250e+03  1.512775e+04
39  시간대21~24매출건수   26178 -1.318500e+03  2.197500e+03
40        남성매출건수   22644 -1.548225e+04  2.671575e+04
41        여성매출건수   22708 -1.514775e+04  2.603825e+04
42     연령대10매출건수   25003 -1.935000e+02  3.225000e+02
43     연령대20매출건수   24172 -3.150000e+03  5.306000e+03
44     연령대30매출건수   23616 -5.624250e+03  9.597750e+03
45     연령대40매출건수   22991 -5.633000e+03  9.735000e+03
46     연령대50매출건수   22541 -6.581250e+03  1.136075e+04
47   연령대60이상매출건수   22776 -6.760000e+03  1.159200e+04

# 분석 변수 정리

In [56]:
# 병합 및 식별에 사용할 컬럼
key_cols = [ '기준년분기코드', '상권코드']

# 업종 단위 데이터에서 사용할 컬럼
industry_key = [ '서비스업종코드' ]

# 전처리 결과 및 최종 검증

In [60]:
datasets = {
    '점포-상권': store_clean,
    '상권변화지표-상권': change_clean,
    '추정매출-상권': sales_clean,
    '추정매출-상권배후지': sales_bg_clean
}

for name, df in datasets.items():

    print(f"===== {name} =====")
    print("데이터 크기:", df.shape)
    print("결측치:",
        df.isnull().sum().sum()
    )
    print("중복값:",
        df.duplicated().sum()
    )
    
print()

===== 점포-상권 =====
데이터 크기: (304775, 14)
결측치: 0
중복값: 0
===== 상권변화지표-상권 =====
데이터 크기: (36300, 11)
결측치: 0
중복값: 0
===== 추정매출-상권 =====
데이터 크기: (85732, 55)
결측치: 0
중복값: 0
===== 추정매출-상권배후지 =====
데이터 크기: (147035, 55)
결측치: 0
중복값: 0